'use strict';

var MyanglishToMyanmarDict = {
    'taung': 'တောင်',
    'tg': 'တောင်',
    'hlae': 'လှည်',
    'kyaung': 'ကြောင်',
    'kyg': 'ကြောင်',
    'thel': 'သဲ',
    'shite': 'ရှိုက်',
    'shate': 'ရှိတ်',
    'shake': 'ရှိတ်',
    'thwal': 'သွယ်',
    'thwel': 'သွဲ',
    'late sar': 'လိပ်စာ',
    'lade sar': 'လိပ်စာ',
    'lame': 'လိမ့်',
    'lane': 'လိန်',
    'yine': 'ရိုင်',
    'yaing': 'ရုင်',
    'san tone kyi': 'စမ်းသုံးကြည့်',
    'san 3 kyi': 'စမ်းသုံးကြည့်',
    'san use kyi': 'စမ်းသုံးကြည့်',
    'san tone kyi kyi': 'စမ်းသုံးကြည့်ကြည့်',
    'san 3 kyi kyi': 'စမ်းသုံးကြည့်ကြည့်',
    'san use kyi kyi': 'စမ်းသုံးကြည့်ကြည့်',
    'san tone kyi san': 'စမ်းသုံးကြည့်စမ်း',
    'san 3 kyi san': 'စမ်းသုံးကြည့်စမ်း',
    'san use kyi san': 'စမ်းသုံးကြည့်စမ်း',
    'san tone kyi kyi san': 'စမ်းသုံးကြည့်ကြည့်စမ်း',
    'san 3 kyi kyi san': 'စမ်းသုံးကြည့်ကြည့်စမ်း',
    'san use kyi kyi san': 'စမ်းသုံးကြည့်ကြည့်စမ်း',
    'kyi kyi': 'ကြည့်ကြည့်',
    'san lote kyi': 'စံလုပ်ကြည့်',
    'san pya': 'စံပြ',
    'lote kyi': 'လုပ်ကြည့်',
    'kyi chin': 'ကြည့်ချင်',
    'san lote': 'စမ်းလုပ်',
    'sann lote': 'စမ်းလုပ်',
    'san kyi san': 'စမ်းကြည့်စမ်း',
    'san kyi kyi san': 'စမ်းကြည့်ကြည့်စမ်း',
    'di ya dl': 'သတိရ',
    'di ya tl': 'သတိရ',
    'p p lr': 'ပြီးပြိလား',
    'p p lar': 'ပြီးပြိလား',
    'san pe': 'စမ်းပြီး',
    'san p': 'စမ်းပြီး',
    'sann p': 'စမ်းပြီး',
    'sann pe': 'စမ်းပြီး',
    'ppl': 'people', 
    'san htar': 'စံထား',
    'htar san': 'ထားစံ', 
    'htr san': 'ထားစံ',
    'htate': 'ထိပ်',
    'htake': 'ထိတ်',
    'da ti ya': 'သတိရ',
    'tha di ya': 'သတိရ',
    'ta ti ya': 'သတိရ',
    'ta di ya': 'သတိရ',
    '3': 'သုံး',
    'use': 'သုံး',
    'digital': 'ဒီဂျစ်တယ်',
    'digital': 'ဒစ်ဂျစ်တယ်',
    '3 sint': 'သုံးဆင့်',
    'san use': 'စမ်းသုံး',
    'use kyi': 'သုံးကြည့်',
    'ka yaing': 'ခရိုင်',
    'lane say': 'လိမ်းဆေး',
    'lanee say': 'လိမ်းဆေး',
    'lane sayy': 'လိမ်းဆေး',
    'lanee sayy': 'လိမ်းဆေး',
    'hle gu': 'လှည်းကူး',
    'man da lay': 'မန္တလေး',
    'may myo': 'မေမြို့',
    'pyin oo lwin': 'ပြင်ဦးလွင်',
    'pol': 'ပြင်ဦးလွင်',
    'hlyaaw': 'လျှော်',
    'hlane': 'လှိမ်',
    'nay yat': 'နေရပ်',
    'nay yet': 'နေရပ်',
    'hlan': 'လှန်',
    'hlar': 'လှာ',
    'nat': 'နဲ',
    "nat'": 'နဲ',
    "nak": 'နဲ',
    "nt": 'နဲ့',
    "nal": 'နည်',
    "nel": 'နည်',
    'nee pya': 'နည်းပြ',
    'ne pya': 'နည်းပြ',
    'ni pya': 'နည်းပြ',
    'mini': 'မီနီ',
    'store': 'စတိုး',
    'nynut': 'ညွှတ်',
    'see lonee nyi nynut': 'စည်းလုံးညီညွှတ်',
    'phyar htwat': 'ဖျာထွက်',
    'coffee': 'ကော်ဖီ',
    'aung kyaung phyar': 'အောင်ကြောင်းဖျာ',
    'rakkine': 'ရခိုင်',
    'ya kkine': 'ရခိုင်',
    'ka yin': 'ကရင်',
    'nyut': 'ညွတ်',
    'par': 'ပါ',
    'd': 'ဒီ',
    'lar': 'လာ',
    'lr': 'လာ',
    'pwe': 'ပွဲ',
    'pwar': 'ပွား',
    'sote yote': 'ဆုတ်ရုတ်',
    'soat yote': 'ဆုတ်ရုတ်',
    'sat su': 'စပ်စု',
    'sat thar': 'ဆတ်သား',
    'set thar': 'ဆတ်သား',
    'set mhwa': 'ဆတ်မွှ',
    'zat': 'ဇက်',
    'zet': 'ဇတ်',
    'tu': 'တူ',
    'share': 'ရှယ်ယာ',
    'sat tu': 'စပ်သူ',
    'a mhat': 'အမှတ်',
    'sat thu': 'စပ်သူ',
    'shal': 'ရှယ်',
    'myan san': 'မြန်ဆန်',
    'hot pot': 'Hot Pot', 
    'eat': 'စား',
    'treat': 'ကြွေး',
    'sa kay': 'စကေး',
    'yet lyar': 'တင်္ယြာ',
    'yet hlyar': 'တင်္ယြာ',
    'yay hlyar': 'တင်္ယြာ',
    'hlyaw': 'လျော်',
    'hlyar': 'လျှာ',
    'khun': 'ခွန်',
    'khwan': 'ခွမ်',
    'myan myan san san': 'မြန်မြန်ဆန်ဆန်',
    'kyo so': 'ကြိုစို',
    'shae': 'ရှယ်',
    'eain yar': 'အိမ်ရာ',
    'yangon': 'ရန်ကုန်',
    'yangon myo': 'ရန်ကုန်မြို့',
    'yangon myo nal': 'ရန်ကုန်မြို့နယ်',
    'welcome from yangon': 'ရန်ကုန်မြို့မှကြိုစိုပါ၏',
    'ei': '၏',
    'ehi': 'အိ',
    'myanglish': 'မြန်ဂင်္လိပ်',
    'ei ei': 'အိ',
    'nga doe': 'ငါတို့',
    'nga so': 'ငါဆို',
    'min doe': 'မင်းတို့',
    'kyunt taw doe': 'ကျွန်တော်တို့',
    'kyunt ma doe': 'ကျွန်တော်တို့',
    'kyun taw doe': 'ကျွန်တော်တို့',
    'kyun ma doe': 'ကျွန်တော်တို့',
    'tu tu': 'တူတူ',
    'a yar': 'အရာ',
    'a khyar': 'အက္ခရာ',
    'a kya sone': 'အကျဆုံး',
    'a kya sonee': 'အကျဆုံး',
    'phoo': 'ဖူး',
    'sap': 'စပ်',
    'pu sap': 'ပူစပ်',
    'pu sat': 'ပူစပ်',
    'pu pu sap sap': 'ပူပူစပ်စပ်',
    'pu pu sat sat': 'ပူပူစပ်စပ်',
    'vu': 'ဘူး',
    'shar htone': 'လျှာထုံ',
    'htone': 'ထုံ',
    'wut': 'ဝတ်',
    'a wut a htae': 'အဝတ်အထည်',
    'kyat ou kyaw': 'ကြက်ဥကြော်',
    'chin sap': 'ချဥ်စပ်', 
    'chin sat': 'ချဥ်စပ်', 
    'chien': 'ချဥ်',
    'chein': 'ချဥ်',
    'pu zun': 'ပုစွန်',
    'chout': 'ခြောက်',
    'chouk': 'ခြောက်',
    'yuu nan': 'ယူနန်',
    'a chin phan': 'အချဥ်ဖမ်း', // အချဥ်ဖမ်း
    'chin phan': 'ချဥ်ဖမ်း', // ချဥ်ဖမ်း
    'shar la kar': 'ရှာလကာ',
    'shway': 'ရွေ့',
    'sann nak': 'စမ်းနဲ့', // လာမစမ်းနဲ့
    'ma sann nak': 'စမ်းနဲ့', // လာမစမ်းနဲ့
    'ma san nak': 'စမ်းနဲ့', // လာမစမ်းနဲ့
    'a htae': 'အထဲ', 
    'tom': 'တွမ်',
    'tum': 'တွန်',
    'a sg': 'အဆောင်',
    'a saung': 'အဆောင်',
    'an': 'အန်', 
    'nan yoe': 'နံရိုး',
    'nan yoo': 'နံရိုး',
    'na yoe': 'နံရိုး',
    'na yoo': 'နံရိုး',
    'byu': 'ဗြူ',
    'bhu': 'ဗြ',
    'kwl': 'ကွဲ',
    'pu paung': 'ပူးပေါင်း',
    'puu paung': 'ပူးပေါင်း',
    'pu pg': 'ပူးပေါင်း',
    'puu pg': 'ပူးပေါင်း',
    'poh':'ပို',
    'pho': 'ဖို',
    'mo': 'မို',
    'po mo':'ပိုမို',
    'htr chin': 'ထားခြင်း',
    'htrr chinn': 'ထားခြင်း',
    'par e': 'ပါ၏',
    'htwin': 'ထွင်',
    'phan':'ဖန်',
    'shar lo': 'ရှာလို့',
    'myo pya': 'မြို့ပြ',
    'myo taw': 'မြို့တော်',
    'myo daw': 'မြို့တော်',
    'myo nal': 'မြို့နယ်',
    'myo sone': 'မျိုးစုံး',
    'sin tu yo mhar': 'ဆင်တူရိုးမှား',
    'sin tu yoe mhar': 'ဆင်တူရိုးမှား',
    'htone san': 'ထုံးစံ',
    'htonee san': 'ထုံးစံ',
    'a sin a lar': 'အစင်အလာ',
    'a sin a lr': 'အစင်အလာ',
    'a ya': 'အရ',
    'bb': 'bye bye',
    'yoe yar': 'ရိုးရာ',
    'kyel': 'ကျဲ',
    'bin': 'ဘင်',
    'bo bo': 'ဘိုဘို',
    'bo yar nyunt': 'ဘိုလ်ရာညွှန့်',
    'bo taw': 'ဘိုးတော်',
    'bo daw': 'ဘိုးတော်',
    'bho': 'ဘိုး',
    'yo yar': 'ရိုးရာ',
    'da tha': 'ဒေသ',
    'da ta': 'ဒေသ',
    'kyay lat': 'ကျေးလက်',
    'yawaw': 'ရွော်',
    'a yaw a sarr': 'အလျာ်အစား',
    'a yaw a sar': 'အလျာ်အစား',
    'yaw kyay': 'လျော်ကြေး',
    'yaw kyae': 'လျော်ကြေး',
    'kyael': 'ကျယ်',
    'a kyae': 'အကျယ်',
    'a kyal': 'အကျယ်',
    'kyal zin': 'ကြယ်ဇင်',
    'kyel zin': 'ကြယ်ဇင်',
    'kyal sin': 'ကြယ်စင်',
    'kyel sin': 'ကြယ်စင်',
    'kyat paung': 'ကြက်ပေါင်း',
    'kyat paungg': 'ကြက်ပေါင်း',
    'nga mote': 'ငါးမုန့်', 
    'ngar mote': 'ငါးမုန့်', 
    'mhol': 'မှိုလ်',
    'mhoel': 'မှိုလ်',
    'mhine': 'မှိုင်',
    'mhoe': 'မှို',
    'ywar': 'ရွာ',
    'kyay ywar': 'ကျေးရွာ',
    'myay': 'မြေ',
    'mwa': 'မွ',
    'kyint': 'ကျင့်',
    'lo so': 'လိုဆို',
    'at lo so': 'လိုဆို',
    'a lo so': 'လိုဆို',
    't lo so': 'လိုဆို',
    'at d lo so': 'အဒီလိုဆို',
    'a d lo so': 'အဒီလိုဆို',
    't d lo so': 'အဒီလိုဆို',
    'at di lo so': 'အဒီလိုဆို',
    'a di lo so': 'အဒီလိုဆို',
    't di lo so': 'အဒီလိုဆို',
    'dr so': 'ဒါဆို',
    'at dr so': 'အဲ့ဒါဆို',
    'at dar so': 'အဲ့ဒါဆို',
    'a dr so': 'အဲ့ဒါဆို',
    'a dar so': 'အဲ့ဒါဆို',
    'so lo': 'ဆိုလို',
    'so lot': 'ဆိုလို့',
    'so lo shi': 'ဆိုလို့ရှိ', //ဆိုလို့ရှိရင်
    'au': 'အူ',
    'an': 'အမ်',
    'ma': 'မ',
    'm': 'မ',
    'lote': 'လုပ်',
    'tay': 'သေ',
    'twr': 'သွာ',
    'twar': 'သွာ',
    'mal': 'မယ်',
    'mel': 'မယ်',
    'min': 'မင်',
    'br': 'ဘာ',
    'bar' : 'ဘာ',
    'chin': 'ချင်',
    'll': 'လဲ',
    'lae': 'လဲ',
    'le': 'လဲ',
    'thu kha': 'သုခ',
    'phit': 'ဖြစ်',
    'phyit': 'ဖြစ်',
    'kwar': 'ကွာ',
    'kwa': 'ကွာ',
    'kyun': 'ကျွန်',
    'yay': 'ရေ',
    'kwr': 'ကွာ',
    'lee': 'လီ',
    'lo': 'လို',
    'loe': 'လိုး',
    'pha': 'ဖ',
    'dog': 'ခွေး',
    'zann': 'စမ်း',
    'nay san': 'နေစမ်း',
    'nay sann': 'နေစမ်း',
    'bae': 'ဘဲ',
    'zain': 'ဇိမ်',
    'phone shwe': 'ဖုန်းရွှေ',
    'oak': 'အုတ်',
    'ote': 'အုပ်',
    'nyar': 'ညာ',
    'ngyar': 'ညာ',
    'kyaw nyar': 'ကြေညာ',
    'kyay nyar': 'ကြေညာ',
    'kyaw ngyar': 'ကြေညာ',
    'kyay ngyar': 'ကြေညာ',
    'tar zan': 'တာဇံ',
    'khway': 'ခွေ',
    'kyatt': 'ကြက်',
    'yone tar': 'ယုန်သား',
    'yone thar': 'ယုန်သား',
    'kyat thar sar': 'ကြက်သားစား',
    'kyat thar ser': 'ကြက်သားစား',
    'kyat tar sar': 'ကြက်သားစား',
    'kyat tar ser': 'ကြက်သားစား',
    'nay': 'နေ',
    'nade': 'နေ့',
    'nate': 'နှိပ်',
    'nhat': 'နှပ်',
    'de': 'တီ',
    'thee': 'တည်',
    'phan thi': 'ဖန်တီး',
    'phan thii': 'ဖန်တီး',
    'phan the': 'ဖန်တီး',
    'phan thee': 'ဖန်တီး',
    'phan tee yar': 'ဖန်တီးရာ',
    'phan dee yar': 'ဖန်တီးရာ',
    'phan de yr': 'ဖန်တီးရာ',
    'phan de yar': 'ဖန်တီးရာ',
    'phan dee yr': 'ဖန်တီးရာ',
    'phan tee yar': 'ဖန်တီးရာ',
    'phan te yr': 'ဖန်တီးရာ',
    'phan te yar': 'ဖန်တီးရာ',
    'phan tee yr': 'ဖန်တီးရာ',
    'phan thi yar': 'ဖန်တီးရာ',
    'phan thi yr': 'ဖန်တီးရာ',
    'phan thi yar': 'ဖန်တီးရာ',
    'phan thi yr': 'ဖန်တီးရာ',
    'kaung': 'ကောင်',
    'shay nay': 'ရှေ့နေ',
    'shayt nay': 'ရှေ့နေ',
    'shayk nay': 'ရှေ့နေ',
    'shet': 'ရှက်',
    'kha': 'ခ',
    'one': 'အုန်',
    'san chaung': 'စမ်းချောင်း',
    'sann chaung': 'စမ်းချောင်း',
    'kg': 'ကောင်',
    'aung': 'အောင်',
    'lu soe': 'လူဆိုး',
    'har': 'ဟာ',
    'hr': 'ဟာ',
    'ha': 'ဟ',
    'ag': 'အောင်',
    'kwal': 'ကွယ်',
    'kwae': 'ကွယ်',
    'myat kwal': 'မျက်ကွယ်',
    'pyu': 'ပြု',
    'mhout': 'မှောက်',
    'hmout': 'မှောက်',
    'myat kwae': 'မျက်ကွယ်',
    'po': 'ပို',
    'omm': 'အွန်',
    'om': 'အွန်',
    'htun': 'ထွန်',
    'touk': 'တောက်',
    'ta lo bal': 'တလိုဘဲ',
    'ta lo bl': 'တလိုဘဲ',
    'ta lo vl': 'တလိုဘဲ',
    'lo bal': 'တလိုဘဲ',
    'haung': 'ဟောင်',
    'tun': 'ထွန်',
    'pu': 'ပူ',
    'pu dl': 'ဖူးတယ်',
    'puu dl': 'ဖူးတယ်',
    'pu dal': 'ဖူးတယ်',
    'puu dal': 'ဖူးတယ်',
    'pu tl': 'ဖူးတယ်',
    'puu tl': 'ဖူးတယ်',
    'pu tal': 'ဖူးတယ်',
    'puu tal': 'ဖူးတယ်',
    'phyu sin': 'ဖြူစင်',
    'nee pyin nyar': 'နည်းပညာ',
    'ne pyin nyar': 'နည်းပညာ',
    'ni pyin nyar': 'နည်းပညာ',
    'kyite': 'ကြိုက်',
    'kyike': 'ကြိုက်',
    'gi ta': 'ဂီတ',
    'gi tar': 'ဂီတာ',
    'ta chin': 'သီချင်း',
    'jyi': 'ဂျီး',
    'may': 'မေ',
    'tway': 'တွေ',
    'aye': 'အေ',
    'nant': 'နမ့်',
    'nant ma tu': 'နမ့်မတူ',
    'nat sin': 'နတ်စင်',
    'chaww dl': 'ချောတယ်',
    'chaww lite': 'ချောလိုက်',
    'chaw dl': 'ချော်တယ်',
    'yoedayar': 'ယိုးဒယား',
    'thai': 'ယိုးဒယား',
    'thailand': 'ယိုးဒယား',
    'hlayar': 'လျား',
    'hlet': 'လျှက်',
    'hlat': 'လျှပ်',
    'nywe': 'နွေ',
    'nwe': 'နွဲ',
    'nhwe': 'နွဲ',
    'nwae': 'နွယ်',
    'ywe': 'ရွဲ',
    'shywe': 'ရွှဲ',
    'yway': 'ရွေ',
    'nwa': 'နွာ',
    'nwar': 'နွား',
    'dwy': 'တွေ',
    'yin': 'ရင်',
    'nga': 'ငါ',
    'lay': 'လေ',
    'oo' : 'ဦ',
    'pyw': 'ပြော',
    'kar': 'ကာ',
    'yal': 'ရဲ',
    'pine': 'ပိုင်',
    'khone': 'ခုန်', 
    'yin khone tan': 'ရင်ခုံန်သံ',
    'choke': 'ချုပ်',
    'mine': 'ငါ့ဥစ္စာ',
    'htein': 'ထိမ်',
    'sein': 'စိမ်',
    'thet': 'သက်',
    'that': 'သတ်',
    'sinn that': 'ဆင်းသက်',
    'sinn thet': 'ဆင်းသက်',
    'sinn tet': 'ဆင်းသက်',
    'sinn tat': 'ဆင်းတတ်',
    'sin paw': 'စင်ပေါ်',
    'chin kite': 'ခြင်ကိုက်',
    'chin daung': 'ခြင်တောင်',
    'chin taung': 'ခြင်တောင်',
    'chin htaung': 'ခြင်ထောင်',
    'chin htg': 'ခြင်ထောင်',
    'taw taung': 'တောတောင်',
    'taw tg': 'တောတောင်',
    'taw tr': 'တောသား',
    'taw kg': 'တောကောင်',
    'taw tar': 'တောသား',
    'taw kaung': 'တောကောင်',
    'taw thar': 'တောသား',
    'taw yine': 'တောရိုင်း',
    'taw yinee': 'တောရိုင်း',
    'a kyo ko saung': 'အကျိုးကိုဆောင်',
    'a kyo ko sg': 'အကျိုးကိုဆောင်',
    'a kyoo ko saung': 'အကျိုးကိုဆောင်',
    'a kyoo ko sg': 'အကျိုးကိုဆောင်',
    'out kya nout kya':'အောက်ကျနောက်ကျ',
    'ma pyay': 'မပြေ',
    'ma pyae': 'မပြည်',
    'ma pyaek': 'မပြည့်',
    'a sin pyay': 'အဆင်ပြေ',
    'a sin pyae': 'အဆင်ပြည်',
    'a sin pyaek': 'အဆငပြည့်',
    'pyaay': 'ပြေ',
    'ma ti': 'မသိ',
    'ma di': 'မသိ',
    'out': 'အောက်',
    'out kya': 'အောက်ကျ',
    'ma ti kya': 'မသိကြ',
    'ma thi kya': 'မတိကျ',
    'animal': 'တိရစ္ဆာန်',
    'shone': 'ရှုံ',
    'mat': 'မတ်',
    'met': 'မက်',
    'htin': 'ထင်',
    'htwe': 'ထွေ',
    'htwae': 'ထွေး',
    'ya yu': 'ရယူ',
    'ya yuu': 'ရယူ',
    'h': 'ဟ',
    'hi': 'ဟိ',
    'he': 'ဟီ',
    'hl': 'ဟဲ',
    'hk': 'ဟဲ့',
    'hal ho': 'ဟယ်ဟိုး',
    'si to': 'ဆီသို့',
    'se to': 'ဆီသို့',
    'to': 'သို့',
    'toe': 'သို့',
    'too': 'သိုး',
    'twe': 'တွယ်',
    'ngwae': 'နွေ',
    'tet': 'သတ်',
    'ti lr': 'သိလား',
    'ti lar': 'သိလား',
    'so dr': 'ဆိုတာ',
    'so tr': 'ဆိုတာ',
    'so tok': 'ဆိုတာ့',
    'so top': 'ဆိုတာ့',
    'so tae': 'ဆိုတဲ့',
    'so te': 'ဆိုတဲ့',
    'lwal': 'လွယ်',
    'ya nay': 'ယနေ့',
    'ta phat': 'တစ်ဖက်', 
    'a sin pyay pyay': 'အဆင်ပြေပြေ',
    'tha': 'သ',
    'pay mae': 'ပေမဲ့',
    'pay mat': 'ပေမဲ့',
    'mh': 'မဟ်',
    'pout': 'ပေါက်',
    'ta baw': 'သဘော',
    'ta baw kg': 'သဘောကောင်း',
    'ta baw kaung': 'သဘောကောင်း',
    'ta baw kaungg': 'သဘောကောင်း',
    'th': 'တစ်',
    'a tan htwat': 'အသံထွက်',
    'sa nit': 'စနစ်',
    'sa khan': 'စခန်း',
    'so tr': 'ဆိုတာ',
    'khann': 'ခန်း',
    'a mway sat khan': 'အမွေဆက်ခံ',
    'sat khan': 'စက်ခန်း',
    'di htet soe': 'ဒီထက်ဆိုး',
    'eain di ya': 'အိိန္ဒိယ',
    'da di': 'သတိ',
    'da di ya': 'သတိရ',
    'da ti ya': 'သတိရ',
    'tan': 'တန်',
    'mwae': 'မွဲ',
    'mwe': 'မြွေ',
    'ton': 'တွန်',
    'toun': 'တွန်',
    'lwae': 'လွဲ',
    'money': 'ပိုက်ဆံ',
    'chaw': 'ချော်',
    'twar chaw': 'သွားချော့',
    'twar chawt': 'သွားချော့',
    'sin lone chaw': 'စင်းလုံးချော',
    'pyan kyaw htar': 'ပြန်ကြော်ထား',
    'eain mat': 'အိမ်မက်',
    'sate ku': 'စိတ်ကူး',
    'sate kuu': 'စိတ်ကူး',
    'ba wa': 'ဘဝ',
    'twayy htoe': 'သွေးထိုး',
    'tway htoe': 'သွေးထိုး',
    'pyaw': 'ပြော',
    'a': 'အ',
    'phyaw': 'ဖျော်',
    'sa': 'ဆ',
    'yar': 'ရာ',
    'yaer': 'ယာ',
    'hin': 'ဟင်',
    'sor': 'ဆော်',
    'sar yar': 'ဆရာ',
    'sayar': 'စရာ',
    'car': 'ကား',
    'cr': 'ကာ',
    'yaw': 'ရော',
    'sin': 'ဆင်',
    'pyay': 'ပြေ',
    'pyi': 'ပြည်',
    'myo': 'မျို',
    'ta': 'တ',
    't': 'တီ',
    'toot': 'တွတ်',
    'tot': 'တော့',
    'phit ti': 'ဖြစ်တည်',
    'phit t': 'ဖြစ်တည်',
    'phit di': 'ဖြစ်တည်',
    'phit d': 'ဖြစ်တည်',
    'shar phwe': 'ရှာဖွေ',
    'shar pwe': 'ရှာပွဲ',
    'shar par': 'ရှာပါ',
    'shar bar': 'ရှာပါ',
    'shar pr': 'ရှာပါ',
    'shar br': 'ရှာပါ',
    'shar par': 'ရှာပါ',
    'sharr parr': 'ရှားပါး',
    'sharr pa': 'ရှားပ',
    'shar pa': 'ရှားပ',
    'sh': 'ရှ်',
    'shoe': 'ရှိုး',
    'show': 'ရှိုး',
    'mho': 'မှို',
    'sel': 'ဆဲ',
    'my': 'မိုင်',
    'y': 'ဝိုင်',
    'ma thar': 'မသာ',
    'ma thar ma': 'မသာမ',
    'yah': 'ယ',
    'kua': 'ကိုယ့်ဘာကို',
    'koa': 'ကိုယ့်ကို',
    'koa ko': 'ကိုယ့်ဘာကို',
    'nay tr': 'နေတာ',
    'nay tar': 'နေတာ',
    'ny tr': 'နေတာ',
    'ny tar': 'နေတာ',
    'ny': 'နေ',
    'phi': 'ဖီ',
    'phe': 'ဖိ',
    'nak so': 'နဲ့ဆို',
    'bite': 'ဗိုက်',
    'byite': 'ဗိုက်',
    'p': 'ပိ',
    'pii': 'ပီ',
    'shote': 'ရှုပ်',
    'shirt': 'ရှပ်',
    'shut': 'ရှပ်',
    'work': 'အလုပ်',
    'htoe': 'ထို',
    'hinn': 'ဟင်',
    'hninn': 'နှင်',
    'a si': 'အဆီ',
    'a nit': 'အနှစ်',
    'si to': 'ဆီသို့', // သူဆီကို
    'si tho': 'ဆီသို့', // သူဆီကို
    'si ko': 'ဆီကို', // သူဆီကို
    'se ko': 'ဆီကို', // သူဆီကို
    'se twar': 'ဆီသွား', // သူဆီသွား
    'si twar': 'ဆီသွား', // သူဆီသွား
    'se po': 'ဆီပို့', // သူဆီပို့
    'si po': 'ဆီပို့', // သူဆီပို့
    'si yout': 'ဆီရောက်', // သူဆီရောက်
    'se yout': 'ဆီရောက်', // သူဆီရောက်
    'se htae': 'ဆီထည်', // သူဆီထည့်
    'se htaek': 'ဆီထည့်', // သူဆီထည့်
    'se htaet': 'ဆီထည့်', // သူဆီထည့်
    'si htae': 'ဆီထည်', // သူဆီထည့်
    'si htaek': 'ဆီထည့်', // သူဆီထည့်
    'si htaet': 'ဆီထည့်', // သူဆီထည့်
    'set si': 'စက်ဆီ',
    'sat si': 'စက်ဆီ',
    'set se': 'စက်ဆီ',
    'sat se': 'စက်ဆီ',
    'dat si': 'ဓါတ်ဆီ',
    'dat se': 'ဓါတ်ဆီ',
    'car si': 'ကားဆီ',
    'car se': 'ကားဆီ',
    'date': 'ဒိတ်',
    'si karr': 'စီကား',
    'so': 'စို',
    'soe': 'စို',
    'wa': 'ဝ',
    'ng': 'နိုင်',
    'naing': 'နိုင်',
    'bu': 'ဘူ',
    'wu': 'ဘူ',
    'tr': 'တာ',
    'kyar': 'ကြာ',
    'kyr': 'ကြာ',
    'pe': 'ပြီ',
    'gi': 'ဂီ',
    'pi': 'ပြိ',
    'naw': 'နော်',
    'lhaw': 'လျော်',
    'hlaw': 'လျော်',
    'hlw': 'လျော်',
    'nor': 'နော်',
    'baung': 'ဘောင်',
    'chin si': 'ချည်စီ',
    'gar': 'ဂါ',
    'gar won': 'ဂါဝန်',
    'bi': 'ဘီ',
    'sha': 'ရှ',
    'yar zar': 'ရာဇာ',
    'hti sha': 'ထိရှ',
    'phywet': 'ဖွတ်',
    'phywat': 'ဖွက်',
    'phwel': 'ဖွဲ',
    'phwat': 'ဖွဲ',
    'goon': 'ဂွန်',
    'gone': 'ဂုံ',
    'gwae': 'ဂွဲ',
    'gwe': 'ဂွေ',
    'gwey': 'ဂွေ',
    'gwa': 'ဂွ',
    'gwat': 'ဂွတ်',
    'gwet': 'ဂွက်',
    'gwan': 'ဂွမ်',
    'hat': 'ဟတ်',
    'het': 'ဟက်',
    'hey': 'ဟေ',
    'gan': 'ဂန်',
    'gan kaw': 'ဂန်ကော်',
    'guon': 'ဂွန်',
    'ka yar': 'ကယား',
    'gaw': 'ဂေါ်',
    'gwar': 'ဂွါ',
    'guu': 'ဂူ',
    'gu': 'ဂု',
    'gun': 'ဂွမ်',
    'ge': 'ဂီ',
    'gn': 'good night',
    'gp': 'group',
    'gm': 'general manager',
    'hr': 'ဟာ',
    'huo': 'ဟှော',
    'hui': 'ဟှေ',
    'hua': 'ဟွာ',
    'hup': 'ဟပ်',
    'hao': 'ဟောင်',
    'haung': 'ဟောင်',
    'hun': 'ဟွန်',
    'horn': 'ဟွန်',
    'hyoun': 'ဟွမ်',
    'hyou': 'ဟွို',
    'hyou': 'ဟွိ',
    'haw': 'ဟော',
    'hap': 'ဟပ်',
    'yar ti ou du': 'ရာသီဥတု',
    'yar ti u tu': 'ရာသီဥတု',
    'yr ti u tu': 'ရာသီဥတု',
    'yr ti ou du': 'ရာသီဥတု',
    'yar t ou du': 'ရာသီဥတု',
    'yar t u tu': 'ရာသီဥတု',
    'yr t u tu': 'ရာသီဥတု',
    'yr t ou du': 'ရာသီဥတု',
    'ytod': 'ရာသီဥတု',
    'ytot': 'ရာသီဥတု',
    'yar ti': 'ရာသီ',
    'yar t': 'ရာသီ',
    'yr t': 'ရာသီ',
    'yr ti': 'ရာသီ',
    'saung yar ti' : 'ဆောင်းရာသီ',
    'saung yar t' : 'ဆောင်းရာသီ',
    'saung yar d' : 'ဆောင်းရာသီ',
    'saung yar di' : 'ဆောင်းရာသီ',
    'saung yr ti' : 'ဆောင်းရာသီ',
    'saung yr t' : 'ဆောင်းရာသီ',
    'saung yr d' : 'ဆောင်းရာသီ',
    'saung yr di' : 'ဆောင်းရာသီ',
    'sg yar ti' : 'ဆောင်းရာသီ',
    'sg yar t' : 'ဆောင်းရာသီ',
    'sg yar d' : 'ဆောင်းရာသီ',
    'sg yar di' : 'ဆောင်းရာသီ',
    'phite': 'ဖြိုက်',
    'phike': 'ဖြိုက်',
    'phyite': 'ဖျိုက်',
    'phyote': 'ဖြုတ်',
    'phyaw': 'ဖျော်',
    'phyaar': 'ဖျား',
    'phyarr': 'ဖျား',
    'ju': 'ဂျူ',
    'be': 'ဘီ',
    'nw': 'နော်',
    'bd': 'မွှေးနေ့',
    'gyi': 'ကြီ',
    'gye': 'ကြီ',
    'kyaw': 'ကျော်',
    'zar': 'ဇာ',
    'mg': 'မောင်',
    'maung': 'မောင်',
    'pin': 'ပင်',
    'pan': 'ပန်',
    'nge': 'ငယ်',
    'nyo': 'ငြို',
    'phin': 'ဖင်',
    'zay': 'စျေ',
    'nhote': 'နှုတ်',
    'note': 'နှတ်',
    'nhat': 'နှက်',
    'nhwar': 'နွှာ',
    'nhone': 'နှုန်း',
    'san chin': 'စမ်းချင်',
    'san lo': 'စမ်းလို့',
    'san lok': 'စမ်းလို့',
    'san kyal': 'ဆန်းကြယ်',
    'sann kyal': 'ဆန်းကြယ်',
    'san khan': 'စမ်းခံ',
    'sann khan': 'စမ်းခံ',
    'khin': 'ခင်',
    'chit': 'ချစ်',
    'tal': 'တယ်',
    'tl': 'တယ်',
    'khan': 'ခံ',
    'cha': 'ချ',
    'thar': 'သာ',
    'thaw': 'သော',
    'pr': 'ပါ',
    'say': 'စေ',
    'chan': 'ချမ်',
    'myae': 'မြေ',
    'ngote': 'ငုတ်',
    'ngoke': 'ငုပ်',
    'bird': 'ငှက်',
    'ngat': 'ငတ်',
    'nghat': 'ငှက်',
    'pyen': 'ပျံ',
    'nhyi': 'ငြီ',
    'nhye': 'ငြီ',
    'nye': 'ငြီ',
    'nyeg':'ငြိ',
    'nyit': 'ညှစ်',
    'nhe': 'နှီ',
    'nhnaw': 'နှော',
    'nhaw': 'နှော်',
    'nhnar': 'နှုာ',
    'nhnote': 'နှုာတ်',
    'nn': 'နန်',
    'nem': 'နမ်',
    'nham': 'နာမ်',
    'nan sar': 'နာမ်စား',
    'nan sr': 'နာမ်စား',
    'ki ri yar': 'ကြိယာ',
    'ka ri yar': 'ကြိယာ',
    'ki re yar': 'ကြိယာ',
    'ka re yar': 'ကြိယာ',
    'ri': 'ရိ',
    'nna': 'န',
    'wi tay tha nna': 'ဝိသေတန',
    'we tay tha nna': 'ဝိသေတန',
    'wi ty tha nna': 'ဝိသေတန',
    'we ty tha nna': 'ဝိသေတန',
    'we ty ta nna': 'ဝိသေတန',
    'we ty ta nna': 'ဝိသေတန',
    'we tay ta nna': 'ဝိသေတန',
    'we tay ta nna': 'ဝိသေတန',
    'wi ty ta nna': 'ဝိသေတန',
    'wi ty ta nna': 'ဝိသေတန',
    'wi tay ta nna': 'ဝိသေတန',
    'wi tay ta nna': 'ဝိသေတန',
    'br tay': 'ဘာတေ',
    'bar tay': 'ဘာတေ',
    'br ty': 'ဘာတေ',
    'bar ty': 'ဘာတေ',
    'tay tay lay': 'သေးသေးလေး',
    'tay lay': 'သေးလေး',
    'ty ty ly': 'သေးသေးလေး',
    'ty ly': 'သေးလေး',
    'tay tay ly': 'သေးသေးလေး',
    'tay ly': 'သေးလေး',
    'ty ty lay': 'သေးသေးလေး',
    'ty lay': 'သေးလေး',
    'tw': 'တာ်',
    'ty': 'သေ',
    'twy': 'တွေ',
    'twi': 'တွီ',
    'thay': 'သေ',
    'tey': 'တေ',
    'pha lae': 'ဖလှည်',
    'pa lae': 'ဖလှည်',
    'pha le': 'ဖလှည်',
    'pa le': 'ဖလှည်',
    'phan mal': 'ဖမ်းမယ်',
    'phan ml': 'ဖမ်းမယ်',
    'lite phan': 'လိုက်ဖမ်း',
    'lite phann': 'လိုက်ဖမ်း',
    'like phan': 'လိုက်ဖမ်း',
    'like phann': 'လိုက်ဖမ်း',
    'le le lr lr': 'လီးလီးလားလား',
    'le lee lr lr': 'လီးလီးလားလား',
    'lee lee lr lr': 'လီးလီးလားလား',
    'lee le lr lr': 'လီးလီးလားလား',
    'le le lar lr': 'လီးလီးလားလား',
    'le lee lr lar': 'လီးလီးလားလား',
    'lee lee lar lr': 'လီးလီးလားလား',
    'lee le lr lar': 'လီးလီးလားလား',
    'lit': 'လစ်',
    'li': 'လိ',
    'lrlr': 'လာလာ',
    'a lar': 'အလာ',
    'chaung soe': 'ချောင်းဆိုး',
    'chaung so': 'ချောင်းဆိုး',
    'ngwe saung': 'ငွေဆောင်',
    'min ga lar saung': 'မင်္ဂလာဆောင်',
    'min ga lar': 'မင်္ဂလာ',
    'phyar pone': 'ဖျာပုံ',
    'ngat pyan': 'ငှက်ပျံ',
    'nghat phyar': 'ငှက်ဖျား',
    'hlaung': 'လှောင်',
    'go': 'ဂို',
    'goal': 'ဂိုလ်',
    'go daung': 'ဂိုလှောင်',
    'steel': 'စတီး',
    'aluminium': 'အလူမီနီယံ',
    'nghat pyan': 'ငှက်ပျံ',
    'moe': 'မို',
    'si': 'စိ',
    'car si nay': 'ကားစီးနေ',
    'khan se': 'ခန်းဆီး',
    'khan si': 'ခန်းဆီး',
    'zi': 'စည်',
    'daw': 'ဒေါ်',
    'san': 'စမ်',
    'sann': 'စန်း',
    'saan': 'စန်း',
    'arm': 'အမ်း',
    'guo': 'ကွော',
    'by': 'ဘိုင်',
    'sr': 'စာ',
    'thi kya lr': 'သိကျလား',
    'ti kya': 'တိကျ',
    'kua ko': 'ကိုယ်ဘာကိုယ်',
    'kua': 'ကိုယ်ဘာကိုယ်',
    'yu sa yar': 'ယူစရာ',
    'yu kya': 'ယူကြ',
    'yu nay kya': 'ယူကြ',
    'pyr': 'ပြာ',
    'on': 'အုံး',
    'khu top': 'အခုတော့',
    'khu tot': 'အခုတော့',
    'kyo lote': 'ကြိုလုပ်',
    'kyo loke': 'ကြိုလုပ်',
    'loud': 'လောက်',
    'lg': 'လောင်',
    'laung': 'လောင်',
    'sin ma pyay bu': 'ဆင်ပြေဘူး',
    'sin pyay': 'ဆင်ပြေ',
    'thel kwel': 'သည်းကွဲ',
    'thel kwal': 'သည်းကွဲ',
    'm thel kwl': 'မသည်းကွဲ',
    'm thel kwel': 'မသည်းကွဲ',
    'su late ml': 'ဆူလိမ့်မယ်',
    'su lane ml': 'ဆူလိမ့်မယ်',
    'su late mal': 'ဆူလိမ့်မယ်',
    'su lane ml': 'ဆူလိမ့်မယ်',
    'su cha': 'ဆုချ',
    'di lo': 'ဒီလို',
    'si nit': 'စနစ်',
    's nit': 'စနစ်',
    'saen': 'ဆန်း',
    'sen': 'ဆန်း',
    'san sa par': 'ဆန်စပါး',
    'san sa bar': 'ဆန်စပါး',
    'san sa pr': 'ဆန်စပါး',
    'san sa br': 'ဆန်စပါး',
    'san thit': 'ဆန်းသစ်',
    'phan de': 'ဖန်တီး',
    'san taw tar': 'စန်းသော်တာ',
    'htea': 'ထဲ',
    'hte': 'ထီ',
    'sann taw tar': 'စန်းသော်တာ',
    'san thaw tar': 'စန်းသော်တာ',
    'sann thaw tar': 'စန်းသော်တာ',
    'am': 'အမ်',
    'su': 'စု',
    'kyi': 'ကြည်',
    'kyan': 'ကျန်',
    'mar': 'မာ',
    'bay': 'ဘေ',
    'yan': 'ရန်',
    'twat': 'တွက်',
    'taw': 'တော်',
    'lite': 'လိုက်',
    'like': 'လိုက်',
    'let': 'လက်',
    'lat sat': 'လတ်ဆက်',
    'khae': 'ခဲ',
    'mwar': 'မွှာ',
    'a mwar': 'အမြွှာ',
    'du': 'ဒူ',
    'the': 'တီ',
    'te': 'သီ',
    'ti': 'သိ',
    'dal': 'တယ်',
    'dl': 'တယ်',
    'me': 'ငါ', 
    'i': 'ငါ',
    'ak': 'အဲ',
    'top': 'တော့',
    'tok': 'တော့',
    'yaum': 'ရမ်',
    'mhr': 'မှာ',
    'mr': 'မှာ',
    'mhar': 'မှာ',
    'tap': 'တတ်',
    'kin': 'ကင်',
    'mae': 'မဲ',
    'tee tat': 'တီးတတ်',
    'tine': 'တိုင်',
    'pat': 'ပတ်',
    'ya': 'ရ',
    'hal': 'ဟဲ',
    'ka': 'က',
    'thi': 'သိ',
    'thant': 'သန့်',
    'than': 'သန်',
    'taw b': 'တော်ပြီ',
    'taw p': 'တော်ပြီ',
    'taw lout p': 'တော်ပြီ',
    'taw lout b': 'တော်ပြီ',
    'taw be': 'တော်ပြီ',
    'taw pe': 'တော်ပြီ',
    'taw lout pe': 'တော်ပြီ',
    'phyan': 'ဖြန်',
    'sayy phyan': 'ဆေးဖြန်း',
    'say phyan': 'ဆေးဖြန်း',
    'mhote': 'မှုတ်',
    'a mhonte': 'အမှုန့်',
    'a mhont': 'အမှုန့်',
    'mhone': 'မှုန်',
    'shoute': 'လျှောက်',
    'shaute': 'လျှောက်',
    'shaut': 'လျှောက်',
    'taw lout be': 'တော်ပြီ',
    'thann gaung yan': 'သန်းခေါင်ယံ',
    'san khant': 'စမ်းခန့်',
    'suu': 'စူး',
    'suu san': 'စူးစမ်း',
    'suu sann': 'စူးစမ်း',
    'lay lar': 'လေ့လာ',
    'kyaung thar': 'ကျောင်းသား',
    'kyg thar': 'ကျောင်းသား',
    'window': 'ပြတင်ပေါက်',
    'lay lr': 'လေ့လာ',
    'pate': 'ပိတ်',
    'tat': 'တတ်',
    'khoe': 'ခို',
    'xnxx': '****',
    'shit': 's**t',
    'tae': 'တဲ့',
    'at': 'အ',
    'pal': 'ပဲ',
    'pl': 'ပဲ',
    'kine': 'ကိုင်',
    'shin': 'ရှင်',
    'ko': 'ကို',
    'myan': 'မြန်',
    'tway': 'တွေ',
    'thate': 'သိပ်',
    'thake': 'သိပ်',
    'kite': 'ကိုက်',
    'htwat': 'ထွက်',
    'tate': 'သိတ်',
    'a ti pay': 'အသိပေး',
    'pr di': 'ပါသည်',
    'pan da': 'ပန်ဒါ',
    'pr ti': 'ပါသည်',
    'ka thy': 'ကေတီ',
    'phout': 'ဖောက်',
    'pyan': 'ပြန်',
    'thitsar': 'သစ္စာ',
    'thisar': 'သစ္စာ',
    'new': 'အသစ်',
    'athit': 'အသစ်',
    'thit': 'သစ်',
    'sat': 'စက်',
    'pyin': 'ပြင်',
    'byin': 'ပျင်',
    'sa': 'စ',
    'sayr': 'စရာ',
    'eain': 'အိမ်',
    'ate': 'အိပ်',
    'sar': 'စာ',
    'pain': 'ပိိန်',
    'shaw': 'လျော',
    'ill': 'ဖျား',
    'bro': 'ဘရို',
    'ser': 'ဆာ',
    'pp': 'ပြီးပြိ',
    'taww': 'တော',
    'tor': 'တော',
    'dr': 'ဒါ',
    'tar': 'တာ',
    'bal': 'ဘယ်',
    'lout': 'လောက်',
    'pa san': 'ပိုက်ဆံ',
    'pi san': 'ပိုက်ဆံ',
    'pike san': 'ပိုက်ဆံ',
    'pite san': 'ပိုက်ဆံ',
    'bay maet taw': 'ဘေးမဲ့တော',
    'bay mae taw': 'ဘေးမဲ့တော',
    'nhine': 'နှိုင်း',
    'hnine': 'နှိုင်း',
    'pite': 'ပိုက်',
    'pike': 'ပိုက်',
    'pyaw so': 'ပြောဆို',
    'pyaw soe': 'ပြောဆို',
    'sat san': 'ဆက်ဆံ',
    'set san': 'ဆက်ဆံ',
    'bain': 'ဘိန်',
    'car bain': 'ကားဘီ',
    'hle': 'လှည်',
    'hle dan': 'လှည်းတန်း',
    'mote': 'မုန်',
    'mote sar': 'မုန့်စား',
    'mote sarr': 'မုန့်စား',
    'kyo': 'ကျို',
    'lr kyo': 'လာကြို',
    'lar kyo': 'လာကြို',
    'gaung': 'ခေါင်း',
    'bo': 'ဗိုလ်',
    'boss': 'ဘောစိ',
    'bossi': 'ဘောစိ',
    'ball': 'ဘော',
    'ball pin': 'ဘောပင်',
    'kyiin': 'ကျင်',
    'ball pen': 'ဘောပင်',
    'hta min': 'ထမင်း',
    'htaung': 'ထောင်',
    'a tan toee': 'အသံတိုး',
    'okay': 'အိုကေ',
    'ok': 'အိုကေ',
    'okk': 'အိုကေကေ',
    '8 b': 'အိပ်ပြီ',
    'dar': 'ဒါ',
    'sofa': 'ဆိုဖါ',
    'mhaw': 'မှော်',
    'hta minn': 'ထမင်း',
    'tan sar': 'တန်ဆာ',
    'pankar': 'ပန်ကာ',
    'rice': 'ထမင်း',
    'shi': 'ရှိ',
    'lwint': 'လွင့်',
    'pay': 'ပေ',
    'a tae': 'အသည်း',
    'a tae kwal': 'အသည်းကွဲ',
    'a taee kwal': 'အသည်းကွဲ',
    'twar dl': 'သွားတယ်',
    'chee': 'ခြည်',
    'yaung': 'ရောင်',
    'chi': 'ခြည်',
    'ar': 'အာ',
    'swan': 'စွမ်',
    'swa': 'စွဲ',
    'in': 'အင်',
    'phyay': 'ဖြည်',
    'bl': 'ဘဲ',
    'vl': 'ဘဲ',
    'vl thu': 'ဘယ်သူ',
    'vl thuk': 'ဘယ်သူ့',
    'mhat': 'မှတ်',
    'tway aye': 'သွေးအေး',
    'saw': 'ဆော',
    'nga saw': 'ဆော်',
    'sawr': 'ဆော်',
    'vd': 'video ',
    'cb': 'chat box ',
    'ko tine': 'ကိုယ်တိုင်',
    'ko ko tine': 'ကိုယ်ကိုယ်တိုင်',
    'ko ko ko': 'ကိုယ့်ကိုယ်ကို',
    'mi mi': 'မိမိ',
    'kyout': 'ကြောက်',
    'kyaut':'ကြောက်',
    'a khu': 'အခု',
    'ya khu': 'ယခု',
    'south': 'ဆောက်',
    'east': 'အရှေ့',
    'la da': 'လဒ',
    'da la': 'ဒလ',
    'ya ku': 'ယခု',
    'law': 'လော',
    'ta law': 'တလော',
    'law law sel': 'လောလောဆယ်',
    'law law sal': 'လောလောဆယ်',
    'law law sl': 'လောလောဆယ်',
    'ako': 'အကို',
    'kyan tr': 'ကျန်တာ',
    'kyan tat': 'ကျန်တဲ့',
    'kyan tae': 'ကျန်တဲ့',
    'kyan te': 'ကျန်တဲ့',
    'kyaan': 'ကျမ်',
    'kyann dl': 'ကြမ်းတယ်',
    'kyann tl': 'ကြမ်းတယ်',
    'pae': 'ပဲ',
    'war ta nar': 'ဝါဿနာ',
    'san kyi': 'စမ်းကြည့်',
    'sann kyi': 'စမ်းကြည့်',
    'os': 'online shopping ',
    'm ya': 'မရ',
    'mon': 'မွန်',
    'ne': 'နီ',
    'ni': 'နီ',
    'pyi': 'ပြည်',
    'pyay': 'ပြည်',
    'pyae': 'ပြည့်',
    'san da': 'စန္ဒ',
    'san dar': 'စန္ဒာ',
    'san di': 'စန္ဒီ',
    'mhain': 'မှိန်',
    'cho mhain': 'ချိုမြိန်',
    'pya': 'ပြ',
    'pyay lae': 'ပြေလည်',
    'pyay pyay lae lae': 'ပြေပြေလည်လည်',
    'pyae pyae lae lae': 'ပြေပြေလည်လည်',
    'phyo': 'ဖြို',
    'kwin': 'ခွင်',
    'kwint': 'ခွင့်',
    'kaw pya': 'ကော်ပြန့်',
    'kaw pyan': 'ကော်ပြန့်',
    'nan': 'နမ်',
    'chain': 'ချိန်', 
    'ngo': 'ငို',
    'kone': 'ကုန်',
    'kone kya': 'ကုန်ကျ',
    'oopamar': 'ဥပမာ',
    'soh': 'ဆို',
    'sone': 'စုံ',
    'lote ngann sin': 'လုပ်ငန်းစဥ်',
    'lote yu': 'လုပ်ယူ',
    'khae b': 'ခဲ့ပြီ',
    'khat b': 'ခဲ့ပြီ',
    'kae b': 'ခဲ့ပြီ',
    'pa khone': 'ပခုံး',
    'thwin': 'သွင်',
    'a chain': 'အချိန်',
    'ek': 'အဲ့',
    'kywat': 'ကြွက်',
    'at d lo': 'အဲ့ဒီလို',
    'kyaar': 'ကျာ',
    'sapat': 'စပက်',
    'lin': 'လင်',
    'lan': 'လမ်',
    'shwe': 'ရွှေ',
    'ti': 'တိ',
    'ti dl': 'သိတယ်',
    'ti dal': 'သိတယ်',
    'thi dl': 'သိတယ်',
    'thi dal': 'သိတယ်',
    'a ti a kya': 'အတိအကျ',
    'ngwar': 'နွာ',
    'zaw': 'ဇော',
    'zaww': 'ဇော်',
    'win': 'ဝင်',
    'khant': 'ခန်',
    'yae': 'ရဲ',
    'bagan': 'ပုဂံ',
    'ban kan': 'ပန်းကန်',
    'yee mhan chat': 'ရည်မှန်းချက်',
    'sway nhwee': 'ဆွေးနွေး',
    'kyee kyat': 'ကြီးကြပ်',
    'ga': 'ဂ',
    '啊di' :'အားတီ',
    '啊may' :'အားမေ',
    '啊ma' :'အားမ',
    'ku sar': 'ကုစား',
    'bar twar': 'ဘား သွား',
    'bar twarr': 'ဘား သွား',
    'one nout': 'ဦးနောက်',
    'khine': 'ခိုင်',
    'tv': 'တီဗီ',
    'yi': 'ရီ',
    'on nout': 'ဦးနောက်',
    'naing ye': 'နာရီ',
    'seint': 'စိမ့်',
    'sayy kyaung nay dl': 'ဆေးကြောင်နေတယ်',
    'sayy kyaung': 'ဆေးကျောင်း',
    'sayy kyaungg': 'ဆေးကျောင်း',
    'a yan taw tr': 'အရမ်းတော်တာ',
    'a yan taw tar': 'အရမ်းတော်တာ',
    'yan taw tar': 'အရမ်းတော်တာ',
    'yan taw tr': 'အရမ်းတော်တာ',
    'yan taw': 'ရမ်းတော်',
    'yaum': 'ရမ်',
    'yan kar': 'ရမ်းကား',
    'yann karr': 'ရမ်းကား',
    'yaum karr': 'ရမ်းကား',
    'yaum kar': 'ရမ်းကား',
    'clock': 'နာရီ',
    'oclock': 'နာရီ',
    "o'clock": 'နာရီ',
    'bay din': 'ဗေဒင်',
    'mile': 'မိုင်',
    'yo': 'ယို',
    'ngar': 'ငှာ',
    'ngrar': 'ငှာ',
    'a ngar': 'အငှား',
    'a ngarr': 'အငှား',
    'permit': 'ပါမြစ်',
    'grant': 'ဂရံ',
    'nagar': 'နဂါး',
    'nagar pyan': 'နဂါးပျံ',
    'at dr': 'အဲ့ဒါ',
    'ek': 'အဲ့',
    'gyay': 'ဂျေး',
    'so yin': 'ဆိုရင်',
    'nhr': 'နှာ',
    'wal': 'ဝယ်',
    'nout': 'နောက်', 
    'ye': 'ရဲ',
    'tone bal': 'တုန်းဘဲ',
    'nay tone bal': 'နေတုန်းဘဲ',
    'chit dal': 'ချစ်တယ်',
    'chit sit': 'ချစ်စစ်',
    'sine': 'ဆိုင်',
    'tone': 'တုန်း',
    'mu': 'မူ', 
    'pat tet': 'ပက်တတ်',
    'pat tat': 'ပက်တတ်',
    'pyit': 'ပြစ်',
    'kae': 'ခဲ',
    'ta gal': 'တကယ်',
    'mone': 'မုန်',
    'ate yay': 'အိပ်ရေး',
    'nga soe': 'ငါဆို',
    'ngr soe': 'ငါဆို',
    'na yout': 'နှယောက်',
    'pyat ta nar': 'ပြဿနာ',
    'pya ta nar': 'ပြဿနာ',
    'pya ta nr': 'ပြဿနာ',
    'pyat ta nr': 'ပြဿနာ',
    'pyat t nar': 'ပြဿနာ',
    'pya t nar': 'ပြဿနာ',
    'pya t nr': 'ပြဿနာ',
    'pyat t nr': 'ပြဿနာ',
    'geyi': 'ကြီ',
    'gei': 'ဂြီ',
    'jei': 'ဂြီ',
    'gee': 'ဂျီ',
    'jee': 'ဂျီ',
    'pt': 'ဖြစ်',
    'pht': 'ဖက်',
    'pit lo': 'ဖြစ်လို့',
    'phit lo': 'ဖြစ်လို့',
    'pht lo': 'ဖြစ်လို့',
    'nga so': 'ငါဆို',
    'ngr so': 'ငါဆို',
    'ma wa': 'မဝ',
    'kwat': 'ကွက်',
    'soe yin': 'စိုးရိမ်',
    'khwat': 'ခွက်',
    'khar': 'ခါ',
    'pyoe': 'ပျို',
    'pyo may': 'ပျိုမေ',
    'pyar': 'ပြာ',
    'myat': 'မြတ်', 
    'myal': 'မြဲ',
    'mya': 'မြ',
    'kan': 'ကန်', 
    'myat kan': 'မျက်ကန်း',
    'myat kann':'မျက်ကန်း',
    'ho': 'ဟို',
    'sont': 'စွန့်',
    'kwat ti bal': 'ကွက်တိဘဲ',
    'kwat ti bl': 'ကွက်တိဘဲ',
    'kwat ti vl': 'ကွက်တိဘဲ',
    'kyae': 'ကြဲ',
    'kyee': 'ကြေး',
    'kyae nat': 'ကြေနပ်',
    'tone lo': 'သုံးလို့',
    'shu': 'ရှူ',
    'phone': 'ဖုန်',
    'phone hta': 'ဖုန်ထ',
    'phone lr': 'ဖုန်းလာ',
    'phone sat': 'ဖုန်းဆက်',
    'phone set': 'ဖုန်းဆက်',
    'phone lr lr hta': 'ဖုန်လာလာထ',
    'phone lar lar hta': 'ဖုန်လာလာထ',
    'it': 'အစ်',
    'is': 'အစ်',
    'it ma': 'အစ်မ',
    'yout kyar': 'ယောကျ်ား',
    'youk kyar': 'ယောကျ်ား',
    'kalayma': 'ကလေးမ',
    'main ma': 'မိန်မ', 
    'thu pone san': 'သူ့ပုံစံ',
    'late': 'လိမ့်',
    'set': 'ဆက်',
    'yote': 'ရုပ်',
    'phat': 'ဖတ်',
    'phet': 'ဖက်',
    'wat': 'ဝက်',
    'pig': 'ဝက်',
    'dr so': 'ဒါဆို',
    'phyone': 'ဖြုံ',
    'htu': 'ထူး',
    'aw': 'အော်',
    'aww': 'အော',
    'lan lan': 'လန်းလန်း',
    'lan lan san san': 'လန်းလန်းဆန်းဆန်း',
    'lann lann san san': 'လန်းလန်းဆန်းဆန်း',
    'lan san': 'လန်းဆန်း',
    'lann san': 'လန်းဆန်း',
    'lann sen': 'လန်းဆန်း',
    'lan sen': 'လန်းဆန်း',
    'nae': 'နဲ့',
    'myint': 'မြင့်',
    'tin': 'တင်',
    'han': 'ဟန်',
    'cho mein': 'ချိုမြိန်',
    'mein': 'မြိန်',
    'mhein': 'မြိန်',
    'kyuu': 'ကျူ',
    'kyu': 'ကြူ',
    'f': 'အဖ်',
    'j': 'ဂျေ',
    'k': 'ကေ',
    'r yu': 'အာယု',
    'ar yu': 'အာယု',
    'a yote ta ya': 'အယုတ်တရ',
    'ta ya': 'တရ',
    'yu ya': 'ယုရ',
    'wi': 'ဝိ',
    'wyaw': 'ဝေါ',
    'wo': 'ဝေါ',
    'sayy khann': 'ဆေးခန်း',
    'say khann': 'ဆေးခန်း',
    'say khan': 'ဆေးခန်း',
    'sayy lite': 'ဆေးလိုက်',
    'sey': 'ဆေ',
    'eain gyi shaw': 'အင်္ကျီလျှော်',
    'shyaw': 'လျှော်',
    'hlwar': 'လွှာ',
    'kyan yay': 'ကြံရေ',
    'kyyan yay': 'ကြံရေ',
    'kyyan': 'ကြံ',
    'myin': 'မြင်',
    'siin': 'ဆင်',
    'siint': 'စင့်',
    'a sin': 'အစင်း',
    'to to': 'တူတူ',
    'towar': 'တွာ',
    'tut': 'တွတ်',
    'khat sin sin': 'ခက်စင်စင်',
    'twa': 'တွ',
    'thwa': 'သွ',
    'thwae': 'သွယ်',
    'nout kya kyan': 'နောက်ကျကျန်',
    'nout kya yin': 'နောက်ကျရင်',
    'nout kya khae': 'နောက်ကျခဲ့',
    'nout kya khat': 'နောက်ကျခဲ့',
    'pwint phyo': 'ဖွင့်ဖြိုး',
    'a sin sin': 'အဆင့်ဆင့်',
    'a si a sin': 'အစီအစဥ်',
    'a si a nit': 'အဆီအနှစ်',
    'a se a nit': 'အဆီအနှစ်',
    'a se': 'အဆီ',
    'ta yar': 'တရာ',
    'ta yarr': 'တရား',
    'mhin': 'မြှင်',
    'ou': 'အူ',
    'phaan': 'ဖမ်',
    'maw': 'မော်',
    'shan': 'ရှမ်',
    'mar lar shan kaww': 'မာလာရှမ်းကော',
    'mar lar shan kaw': 'မာလာရှမ်းကော',
    'mr lar shan kaw': 'မာလာရှမ်းကော',
    'mar lr shan kaw': 'မာလာရှမ်းကော',
    'mr lr shan kaw': 'မာလာရှမ်းကော',
    'oo sin': 'ဦးစဥ်း',
    'sin sar': 'စဥ်းစား',
    'sin sarr': 'စဥ်းစား',
    'sinn sar': 'စဥ်းစား',
    'sinn sarr': 'စဥ်းစား',
    'sin chin': 'ဆင်ခြင်',
    'chaung': 'ချောင်',
    'sar phat': 'စာဖတ်',
    'phat sar': 'ဖတ်စာ',
    'nyun': 'ညွှန်',
    'ti pr dl': 'သိပါတယ်',
    'khit': 'ခေတ်',
    'di sout': 'တည်ဆောက်',
    'ti sout': 'တည်ဆောက်',
    'the sout': 'တည်ဆောက်',
    'pyan phan': 'ပြန်ဖမ်း',
    'phan si': 'ဖမ်းဆီး',
    'phan se': 'ဖမ်းဆီး',
    'hta': 'ထ',
    'ann': 'အံ',
    'ant': 'အံ',
    'an aw': 'အန့်အေား',
    'ant aw': 'အန့်အေား',
    'an aww': 'အန့်အေား',
    'ant aww': 'အန့်အေား',
    'nas': 'နက်',
    'net': 'နက်',
    'a nat': 'အနက်',
    'shine': 'ရှိုင်',
    'nyn': 'ညံ',
    'din': 'ဒင်',
    'bo': 'ဗိုလ်',
    'bo gyoke': 'ဗိုလ်ချုပ်',
    'hlaing': 'လှိုင်',
    'mhe': 'မှီ',
    'toe tat': 'တိုးတတ်',
    'toee tat': 'တိုးတတ်',
    'tat taw': 'တတ်သော',
    'khit mhe toe tat taw': 'ခေတ်မှီတိုးတတ်သော',
    'mhan': 'မှန်',
    'myanmar': 'မြန်မာ',
    'mha': 'မှ',
    'htan': 'ထမ်',
    'htan yay': 'ထန်းရည်',
    'eain tar': 'အိမ်သာ',
    'yu lite': 'ယူလိုက်',
    'yu like': 'ယူလိုက်',
    'thut': 'သွတ်',
    'yuu thut': 'ယူသွပ်',
    'thut pyar': 'သွပ်ပြား',
    'thut pyarr': 'သွပ်ပြား',
    'cho': 'ချို',
    'ngan': 'ငံ',
    'htae': "ထည်",
    'ta min': 'တမင်',
    'ta chaut': 'တစ်ခြပ်',
    'thein': 'သိန်',
    'phyu': 'ဖြူ',
    'phwe': 'ဖွေ',
    'tat tat': 'တတ်တတ်',
    'a tone': 'အသုံး',
    'so tar': 'ဆိုတာ',
    'so tr': 'ဆိုတာ',
    'soe tar': 'ဆိုတာ',
    'so tar': 'ဆိုတာ',
    'a tone cha': 'အသုံးချ',
    'a lin yaung': 'အလင်းအရာင်',
    'lin yaung': 'လင်းရောင်',
    'lin yaung chi': 'လင်းရောင်ခြည်',
    'lin yaung che': 'လင်းရောင်ခြည်',
    'so pe': 'ဆိုပြီး',
    'pyone': 'ပြုံ',
    'a ti': 'အတည်',
    'a ti pyaw': 'အတည်ပြော',
    'hote': 'ဟုတ်',
    'myar': 'မျာ',
    'myr': 'မျာ',
    'swar': 'စွာ',
    'swr': 'စွာ',
    'tan yar': 'တန်ရာ',
    'yat': 'ရက်',
    'than': 'သန်',
    'phyat': 'ဖြတ်',
    'paung': 'ပေါင်',
    'pyor': 'ပျော်',
    'shwin': 'ရွှင်',
    'lwan': 'လွမ်',
    'hlwan': 'လွှမ်',
    'eain chan': 'အိမ်ခြံ',
    'eain chan myae': 'အိမ်ခြံမြေ',
    'a kyo saung': 'အကျိုးဆောင်',
    'a kyoo saung': 'အကျိုးဆောင်',
    'thu': 'သူ',
    'a yan': 'အရမ်း',
    'a yann': 'အရမ်း',
    'no smoke': 'ဆေးလိပ်မသောက်ရ',
    'sin nhwe': 'ဆင်နွဲ',
    'you': 'နင်',
    'toon': 'တွန်း',
    'yoon': 'ယွန်း',
    'smoke': 'အငွေ့',
    'htet': 'ထက်',
    'kya': 'ကြ',
    'thin': 'သင်',
    'lat htat': 'လက်ထပ်',
    'htat': 'ထပ်',
    'lite phyat': 'လိုက်ဖျက်',
    'like phyat': 'လိုက်ဖျက်',
    'doe': 'ဒို',
    'lat': 'လက်',
    'latt': 'လတ်',
    'twae': 'တွဲ',
    'twael': 'တွယ်',
    'mi': 'မိ',
    'at lo': 'အဲ့လို',
    'at di': 'အဲ့ဒီ',
    'phone ll sat': 'ဖုန်းလဲဆက်',
    'way': 'ဝေ',
    's': 'စ',
    'sp': 'စပ်',
    'ko bal': 'ကိုဘဲ',
    'ko bl': 'ကိုဘဲ',
    'ko vl': 'ကိုဘဲ',
    'byaw': 'ဗြော်',
    'b': 'ဘိ',
    'kana': 'ခန',
    'ml': 'မယ်',
    'call': 'ခေါ်',
    'kall': 'ခေါ်',
    'a thet': 'အသက်',
    'ta kal': 'တကယ်',
    'saung': 'စောင်',
    'saung nay': 'ဆောင့်နေ',
    'saung ml': 'ဆောင့်မယ်',
    'saung mal': 'ဆောင့်မယ်',
    'kana saung': 'ခနဆောင့်',
    'phyar': 'ဖြား',
    'di': 'ဒီ',
    'own': 'အုံး',
    'shay': 'ရှည်',
    'shat': 'ရှတ်',
    'tayout': 'တစ်ယောက်',
    'tayote': 'တရုတ်',
    'thu thu': 'တူတူ',
    'computer':'ကွန်ပြူတာ',
    'khout': 'ခေါက်',
    'yu ll': 'ယူလဲ',
    'yuu ll': 'ယူလဲ',
    'lout kya': 'လောက်ကျ', // ဘယ်လောက်ကျလဲ
    'dine': 'ဒိုင်',
    'nay dr': 'နေတာ', // ဒါပဲလုပ်နေတာမလား
    'kyaaw': 'ကြော်',
    'py ml': 'ပေးမယ်',
    'pay ml': 'ပေးမယ်',
    'py mal': 'ပေးမယ်',
    'payy ml': 'ပေးမယ်',
    'payy mal': 'ပေးမယ်',
    'py mt': 'ပေမဲ့',
    'pay mt': 'ပေမဲ့',
    'py mat': 'ပေမဲ့',
    'pay mat': 'ပေမဲ့',
    'a py': 'အပေး',
    'a py a yu': 'အပေးအယူ',
    'a yu': 'အယူ',
    'ly': 'လေ',
    'frd': 'သူငယ်ချင်း',
    'sar chin': 'စားချင်',
    'ta ku ku': 'တစ်ခုခု',
    't ku ku': 'တစ်ခုခု',
    'ta khu khu': 'တစ်ခုခု',
    't khu khu': 'တစ်ခုခု',
    'ta ku ku s': 'တစ်ခုခုဆို',
    't ku ku s': 'တစ်ခုခုဆို',
    'ta khu khu s': 'တစ်ခုခုဆို',
    't khu khu s': 'တစ်ခုခုဆို',
    'ta ku ku so': 'တစ်ခုခုဆို',
    't ku ku so': 'တစ်ခုခုဆို',
    'ta khu khu so': 'တစ်ခုခုဆို',
    't khu khu so': 'တစ်ခုခုဆို',
    'myan sone':'မြန်ဆုံး',
    'a yin sone': 'အရင်ဆုံး',
    'ar lone': 'အားလုံး',
    'thae su': 'သဲစု',
    'py ya': 'ပေးရ',
    'pay ya': 'ပေးရ',
    'ma lr': 'မလား',
    'ma lar': 'မလား',
    'm lr': 'မလား',
    'm lar': 'မလား',
    'ku hti': 'အခုထိ',
    'khu hti': 'အခုထိ',
    'ku ti': 'အခုထိ',
    'khu ti': 'အခုထိ',
    'p lr': 'ပြီလား',
    'p lar': 'ပြီလား',
    'sar p': 'စားပြီ',
    'sat pat': '****',
    'sat pat lo': '******',
    'sat pat loe': '******',
    'ky': 'ကျေ',
    'ky nat': 'ကြေနပ်',
    'kay nat': 'ကြေနပ်',
    'myl': 'မြဲ',
    'a myl': 'အမြဲ',
    'lo lr': 'လို့လား',
    'lo ya lr': 'လို့ရလား',
    'rl': 'အလ်',
    'ae lae': 'အယ်လဲ',
    'a lae': 'အယ်လဲ',
    'ae ll': 'အယ်လဲ',
    'a ll': 'အယ်လဲ',
    's k': 's ကောင်',
    's k m': 's ကောင်မ',
    'st k': 's ကောင်',
    'st k m': 's ကောင်မ',
    's k ma': 's ကောင်မ',
    'st k ma': 's ကောင်မ',
    's kg': 's ကောင်',
    's kg m': 's ကောင်မ',
    'st kg': 's ကောင်',
    'st kg m': 's ကောင်မ',
    's kg ma': 's ကောင်မ',
    'st kg ma': 's ကောင်မ',
    'st kg': 's ကောင်',
    'st kg m': 's ကောင်မ',
    'kg ma': 'ကောင်မ',
    'kg lay': 'ကောင်လေး',
    'kg ly': 'ကောင်လေး',
    'st': 'စောက်',
    'dr kg': 'ဒါကြောင့်',
    'di kg': 'ဒီကောင်',
    'thr': 'သာ',
    'loke': 'လုတ်',
    'a chint': 'အချစ်',
    'cht': 'ချစ်',
    'a cht': 'အချစ်',
    'lhone': 'လုန်',
    'lhit': 'လျစ်',
    'hlit': 'လျစ်',
    'kh na': 'ခဏ',
    'laae': 'လည်',
    'llae': 'လည်း',
    'ka lae': 'ကလည်း',
    'ka ll': 'ကလည်း',
    'kn': 'ကမ်',
    'phay': 'ဖေ',
    'tami': 'သမီး',
    'ta mi': 'သမီး',
    'jie': 'ကျဲ',
    'tout': 'သောက်',
    'tone yay': 'သုံးရေ',
    'a tone pyu': 'အသုံးပြု',
    'phu': 'ဖူ',
    'phue': 'ဖူး',
    'phuu': 'ပူ',
    'ngr': 'ငါ',
    'shar': 'လျှာ',
    'shr': 'ရှာ',
    'sout': 'စောက်',
    'shout': 'ရှောက်',
    'shout ti': 'ရှောက်သီး',
    'shout te': 'ရှောက်သီး',
    'yu': 'ရူ',
    'yu pr': 'ယူပါ',
    'yu par': 'ယူပါ',
    'chu': 'ခြူ',
    'chu char': 'ခြူချာ',
    'baw': 'ဘော',
    'tote': 'သုတ်',
    'pone': 'ပုံ',
    'tate tate pone': 'တိတ်တိတ်ပုန်း',
    'lin ma yar': 'လင်မယား',
    'pone pyin': 'ပုံပြင်',
    'kyin': 'ကြင်',
    'kyin phaw': 'ကြင်ဖေါ်',
    'phaw': 'ဖေါ်',
    'tout yay thant': 'သောက်ရေသန့်',
    'sayy tout': 'ဆေးသောက်',
    'sayy lal tout': 'ဆေးလဲသောက်',
    'sayy ll tout': 'ဆေးလဲသောက်',
    'a sar': 'အစာ',
    'a har ya': 'အဟာရ',
    'ar toe say': 'အားတိုးဆေး',
    'arr toe say': 'အားတိုးဆေး',
    'ar toee say': 'အားတိုးဆေး',
    'arr toee say': 'အားတိုးဆေး',
    'kout': 'ကောက်',
    'yoe': 'ရို',
    'pyat thar': 'ပြတ်သား', 
    'pyat tar': 'ပြတ်သား', 
    'tone ma ya': 'သုံးမရ',
    'yone': 'ရုံ',
    'yout': 'ရောက်',
    'noe': 'နို', 
    'no': 'နိုး',
    'lant': 'လန့်',
    'nya': 'ည',
    'nyaw': 'နွှာ်',
    'lone': 'လုံ',
    'hnint': 'နှင့်', 
    'paw': 'ပေါ',
    'pawt': 'ပေါ့',
    'kwall': 'ကွဲ',
    'ku tha': 'ကုသ',
    'paw sa': 'ပေါ့ဆ',
    'nit ko': 'နင့်ကို',
    'ku': 'ကူ',
    'kku': 'ကု',
    'nit thit ku': 'နှစ်သစ်ကူး',
    'pawt sa': 'ပေါ့ဆ',
    'a nit': 'အနှစ်',
    'ta lote sar': 'တစ်လုတ်စာ', 
    'lote sar': 'လုတ်စာ',
    'phoe': 'ဖိုး',
    'paw sa nit': 'ပေါ့ဆနှင့်',
    'pawt sa nit': 'ပေါ့ဆနှင့်',
    'gayu': 'ဂရု',
    'gayu site': 'ဂရုစိုက်',
    'gayu sike': 'ဂရုစိုက်',
    'pyo': 'ပျို',
    'pyout': 'ပျောက်',
    'pye': 'ပြဲ',
    'pyt': 'ပျက်',
    'pyot': 'ပျော့',
    'wine': 'ဝိုင်',
    'ti shi': 'သိရှိ',
    'ng chin': 'နိုင်ခြင်း',
    'ng chinn': 'နိုင်ခြင်း',
    'naing chin': 'နိုင်ခြင်း',
    'naing chinn': 'နိုင်ခြင်း',
    'lr chinn': 'လာခြင်း',
    'lar chinn': 'လာခြင်း',
    'da tar': 'ဒေတာ',
    'ning': 'နင်',
    'nig': 'နဂ်',
    'nih': 'နဟ်',
    'phyay shin': 'ဖြေရှင်း',
    'phyay shinn': 'ဖြေရှင်း',
    'phyay si': 'ဖြည့်ဆီး',
    'phyay se': 'ဖြည့်ဆီး',
    'swat': 'စွက်',
    'pote': 'ပုဒ်',
    'eei': 'ဤ',
    'yyway': '၍',
    'ngao': 'ငေါင်',
    'ngaung': 'ငေါင်',
    'nyin': 'ငင်',
    'ngin': 'ငင်',
    'nget': 'ငက်',
    'pote go': 'ပုဂ္ဂိုလ်',
    'ya chin': 'ရခြင်း',
    'ya chinn': 'ရခြင်း',
    'tay yar pr': 'သေရာပါ',
    'tay yar par': 'သေရာပါ',
    'tay yr par': 'သေရာပါ',
    'tay yr pr': 'သေရာပါ',
    'tay yr par': 'သေရာပါ',
    'htae sin': 'ထဲဆင်း',
    'gyar': 'ကြား',
    'lion': 'ခြင်္သေ့',
    'tha min': 'တမင်',
    'a khann': 'အခန်း',
    'u': 'ဦ',
    'l': 'လ',
    'z': 'ဇက်',
    'za': 'ဇ',
    'c': 'စီ',
    'g': 'ဂျီ',
    'o': 'အို',
    'r': 'အာ',
    'v': 'ဗီ',
    'zein': 'ဇိမ်',
    'sein ta lone': 'စိန်တစ်လုံး',
    'sein ta': 'စိန်တစ်',
    'sein lat soot': 'စိန်လက်စွပ်',
    'sein lat kout': 'စိန်လက်ကောက်',
    'kou': 'ခို',
    'koh': 'ခို',
    'at ku': 'တခု',
    'tat ku': 'တစ်ခု',
    'ze': 'ဇိ',
    'zee': 'ဇီး',
    'se': 'စည်',
    'see': 'ဆီ',
    'si mhan':'စီမံ',
    'kyat': 'ကျပ်', 
    'aya': 'အေ',
    'ay': 'အေ',
    'da': 'ဒ',
    'du': 'ဒူ',
    'rs': 'relationship',
    'mway': 'မွေ',
    'snake': 'မြွှေ',
    'du won': 'ဒူဝံ',
    'key': 'ကီ',
    'ki': 'ကိ',
    'monkey': 'မျောက်',
    'wow': 'ဝေါ',
    'wote': 'ဝုတ်',
    'what': 'ဝှက်',
    'wha': 'ဝ',
    'wa': 'ဝ',
    'w': 'ဝ',
    'q': 'ကြူ',
    'nk': 'နဲ့',
    'yel': 'ရယ်',
    'yee': 'ရီ',
    'yal ya': 'ရယ်ရ',
    'ye ya': 'ရယ်ရ',
    'yee ya': 'ရယ်ရ',
    'yi ya': 'ရယ်ရ',
    'yal ya dl': 'ရယ်ရတယ်',
    'ye ya dl': 'ရယ်ရတယ်',
    'yee ya dl': 'ရယ်ရတယ်',
    'yal ya tl': 'ရယ်ရတယ်',
    'ye ya tl': 'ရယ်ရတယ်',
    'yee ya tl': 'ရယ်ရတယ်',
    'du won kyae': 'ဒူဝံကြယ်',
    'du won kyal': 'ဒူဝံကြယ်',
    'ak kyg': 'အဲ့တာကြာင့်',
    'at kyg': 'အဲ့တာကြာင့်',
    'ak a kyg': 'အဲ့အကြာင်း',
    'at a kyg': 'အဲ့အကြာင်း',
    'site': 'ဆိုက်',
    'sike': 'ဆိုက်',
    'size': 'ဆိုဒ်',
    'guide': 'guide ',
    'ngwe': 'ငွေ',
    'kyaee': 'ကြေး', 
    'mee pu': 'မီးပူ',
    'me pu': 'မီးပူ',
    'kyay': 'ကြေး', 
    'oh': 'အို',
    'gone yay': 'ဂုန်ရည်',
    'gone yi': 'ဂုန်ရည်',
    'gon': 'ဂုန်',
    'war': 'ဝါး',
    'wae': 'ဝဲ',
    'kun': 'ကွန်',
    'mhya':'မျ',
    'kwan': 'ကွမ်',
    'lo tl':'လိုတယ်',
    "lu'": 'လု',
    'lu yu': 'လုယူ',
    'lu yuu': 'လုယူ',
    'tldr': "too long; don't read",
    'loate': 'လုတ်',
    'lote tine': 'လုပ်တိုင်း',
    'thouk': 'သောက်',
    'long': 'ရှည်',
    'long long ago': 'ဟိုအရင်က',
    'lote ngan': 'လုပ်ငန်း',
    'lote ngann': 'လုပ်ငန်း',
    'war htein': 'ဝါထိန်',
    'lwin': 'လွင်',
    'than lwin': 'တလွင်',
    'pyin nyar': 'ပညာ',
    'myor': 'မျှော်',
    'myol': 'မျိုး',
    'ta charr': 'သေချာ',
    'a mhike d yite': 'အမှိုက်ဒရိုက်',
    'a mhike da yite': 'အမှိုက်ဒရိုက်',
    'a mhite d yite': 'အမှိုက်ဒရိုက်',
    'a mhite da yite': 'အမှိုက်ဒရိုက်',
    'mhyu': 'မြှု',
    'mhyuu': 'မြှူ',
    'mhyar': 'မြား',
    'myu': 'မြူ',
    'myote': 'မြှုတ်',
    'myode': 'မြှုပ်',
    'a myode': 'အမြှုပ်',
    'myay myote': 'မြေမြုတ်',
    'kyal': 'ကျယ်',
    'san dl': 'ဆန်တယ်',
    'kye': 'ကျီ',
    'bicycle': 'စက်ဘီ',
    'mhite': 'မှိုက်',
    'mhike': 'မှိုက်',
    'doctor': 'ဒေါက်တာ',
    'da lay': 'ဓလေ့',
    'oe': 'အိုး',
    'bone': 'ဗုံ',
    'bhone': 'ဘုန်',
    'sa bain': 'စက်ဘီ',
    'sa bee': 'စက်ဘီ',
    'tha di': 'သတိ',
    'baing': 'ဗိုင်',
    'bine': 'ဗိုင်',
    'sit': 'စစ်',
    'pyay pyay lae lae': 'ပြေပြေလည်လည်',
    'kol': 'ကိုယ်',
    'swunt kyae': 'စွန့်ကြဲ',
    'pay kann': 'ပေးကမ်း',
    'payy kann': 'ပေးကမ်း',
    'pay kan': 'ပေးကမ်း',
    'payy kan': 'ပေးကမ်း',
    'kyut': 'ကျွတ်',
    'kyouk': 'ကြွတ်',
    'kyut sat': 'ကြွပ်ဆက်',
    'kyut ywa': 'ကြွပ်ရွ',
    'da din': 'သတင်း',
    'da tin': 'သတင်း',
    'tha din kyut': 'သီတင်းကျွတ်',
    'thin gyan': 'သင်္ကြန်',
    'tha zaung mone': 'တန်းဆောင်မုန်း',
    'tha zaung tine': 'တန်းဆောင်တိုင်',
    'tha zaung dine': 'တန်းဆောင်တိုင်',
    'tha saung': 'တန်ဆောင်း',
    'shar saung lat pat': 'ရှားဆောင်းလက်ပတ်',
    'moke ou': 'မုဒ်ဦး',
    'dan': 'ဒဏ်',
    'dan yar': 'ဒဏ်ရာ',
    'dan pyit se': 'ဒန်ပစ္စည်း',
    'dan oh': 'ဒန်အိုး',
    'pyit se': 'ပစ္စည်း',
    'thing': 'ပစ္စည်း',
    'current': 'ပစ္စုပန်',
    'pyit soat pan': 'ပစ္စုပန်',
    'soat': 'ဆုတ်',
    'dae': 'ဒယ်',
    'moke': 'မုဒ်',
    'kem': 'ကမ်',
    'ywa': 'ရွ',
    'myinn': 'မျှင်',
    'kye kan': 'ကျီးကန်း',
    'san chi myinn': 'ဆံချီမျှင်',
    'nu': 'နု',
    'dat': 'ဓါတ်',
    'dhat': 'ဓါတ်',
    'pha': 'ဖ',
    'pha yar': 'ဘုရား',
    'ph yar': 'ဘုရား',
    'daw ta': 'ဒေါ်ဒ',
    'daw da': 'ဒေါ်ဒ',
    'sin thu taw': 'ဆင်းတုတော်',
    'sinn thu taw': 'ဆင်းတုတော်',
    'sin tu taw': 'ဆင်းတုတော်',
    'sinn tu taw': 'ဆင်းတုတော်',
    'si sine': 'ဆီဆိုင်',
    'ta baw ta bar wa': 'တစ်ဘောတစ်ဘဝ',
    'thway': 'သွေ',
    'twe': 'တွဲ',
    'twel': 'တွဲ',
    'twal': 'တွဲ',
    'sone twe': 'စုံတွဲ',
    'sone twel': 'စုံတွဲ',
    'sone twal': 'စုံတွဲ',
    'kyone': 'ကြုံ',
    'kyant': 'ကြံ',
    'kyan yar': 'ကြံရာ',
    'thone': 'သုန်',
    'thoke': 'သုတ်',
    'tote': 'တုတ်',
    'dote': 'တုတ်',
    'thote': 'သုပ်', 
    'song': 'သီချင်း',
    'sonne': 'ဆုံ',
    'a kyan': 'အကြံ',
    'thwe': 'တွယ်',
    'kwun': 'ကွမ်',
    'british': 'ဗြိသျှ',
    'china': 'တရုတ်',
    'american': 'အမေရိကန်',
    'zwe': 'ဇွဲ',
    'meter': 'မီတာ',
    'kyo sar': 'ကြိုးစား',
    'kyoo sar': 'ကြိုးစား',
    'kyoo sarr': 'ကြိုးစား',
    'kyo sarr': 'ကြိုးစား',
    'kyoe': 'ကြိုး',
    'zu': 'ဇူ',
    'kyay zu': 'ကျေးဇူး',
    'kyay zuu': 'ကျေးဇူး',
    'kyayy zu': 'ကျေးဇူး',
    'dwi ha': 'ဒွိဟ',
    'burma': 'ဗမာ',
    'singapore': 'စင်္ကာပူ',
    'hto': 'ထူ',
    'char': 'ခြာ',
    'door': 'တံခါး',
    'ta kar': 'တံခါး',
    'da kar': 'တံခါး',
    'da kar phwint': 'တံခါးဖွင့်',
    'phwint': 'ဖွင်',
    'ngon': 'ငုံ',
    'ngone': 'ငုံ',
    'pwint': 'ပွင်',
    'myat nar': 'မျက်နှာ',
    'a loot kyat': 'အလွတ်ကျက်', 
    'ta bar thu': 'တစ်ပါးသူ',
    'nay sin': 'နေစဥ်',
    'ya ag yu': 'ရအောင်ယူ',
    'nhar': 'နှာ',
    'kyain': 'ကြိမ်',
    'ag yu': 'အောင်ယူ',
    'sote': 'စုတ်',
    'soate': 'စုပ်',
    'sote tan': 'စုတ်တံ',
    'sote ma lr': 'ဆုတ်မလား',
    'mhwe': 'မွှေး',
    'mhway': 'မွှေ',
    'at': 'အပ်',
    'pyat se': 'ပျက်ဆီး',
    'phwar': 'ဖွား',
    'pop': 'ပေါ့',
    'pyat': 'ပျက်',
    'br kyan': 'ဘာကျန်',
    'lo yar': 'လိုရာ',
    'lo tr': 'လိုတာ',
    'sar kyat': 'စာကျက်',
    'kyat sar': 'ကျက်စာ',
    'see sar': 'ဆည်ဆာ',
    'htar na': 'ဌာန',
    'khon': 'ခွန်',
    'khon arr': 'ခွန်အား',
    'toe': 'တို',
    'a tote': 'အသုတ်',
    'sate': 'စိတ်',
    'sate soe': 'စိတ်ဆိုး',
    'sate soee': 'စိတ်ဆိုး',
    'khwal': 'ခွဲ',
    'won': 'ဝန်',
    'play': 'ဆော့',
    'hti': 'ထိ',
    'htine': 'ထိုင်',
    'khu': 'ခု',
    'lane': 'လိမ်', 
    'lane mar': 'လိမ်မာ',
    'pyaung': 'ပြောင်', 
    'pyg': 'ပြောင်', 
    'nin': 'နင်',
    'mhaung':'မှောင်',
    'twin': 'တွင်',
    'kar la': 'ကာလ',
    'ka lar': 'ကုလား',
    'ka la ma': 'ကုလားမ',
    'a ka yar': 'အက္ခရာ',
    'hmaung':'မှောင်',
    'wai': 'ဝေ',
    'wai yan': 'ဝေယံ',
    'moe yan': 'မိုးယံ',
    'moee yan': 'မိုးယံ',
    'thoe': 'သိုး',
    'htael': 'ထည်',
    'nhant': 'နှမ့်',
    'nhan': 'နှမ်း',
    'nhint': 'နှင့်',
    'ai': 'အိုင်',
    'ywal': 'ရွယ်',
    'sot': 'ဆော့',
    'a la': 'အလ',
    'la': 'လ',
    'bala': 'ဗလ',
    'ba': 'ဘ',
    'nyein': 'ငြိမ်',
    'hair': 'ဆံပင်',
    'eain dra': 'အန္ဒြာ',
    'bank': 'ဘဏ်',
    'ban':  'ဗန်',
    'zay ban': 'စျေးဗန်း',
    'a ba': 'အဘ',
    'aya yar waddy': 'Aya yar waddy',
    'kr': 'ကား',
    'a la kr': 'အလကား',
    'a la kar': 'အလကား',
    'nyi': 'ညီ',
    'nyi lay': 'ညီလေး',
    'nyi ma lay': 'ညီလေး',
    'kyma': 'ကျွန်မ',
    'kyun ma': 'ကျွန်မ',
    'kytaw': 'ကျွန်တော်',
    'kyun taw': 'ကျွန်တော်',
    'taww tar': 'တေားသား',
    'lat kar': 'လက်ကား',
    'la kar': 'လကား',
    'la kar kaung': 'အလကားကောင်',
    'dagon': 'ဒဂုံ',
    'myout': 'မြှောက်',
    'a shay': 'အရှေ့',
    'a nout': 'အနောက်',
    'che pr': 'ချီးပါ',
    'chyet': 'ချပ်',
    'chet': 'ချတ်',
    "kya'":'ကျ', 
    'chee pr': 'ချီးပါ',
    'chi pr': 'ချီးပါ',
    'che': 'ချီ',
    'e': 'အီ',
    'ee': 'အီး',
    'shaung': 'ရှောင်',
    'yin kwin': 'ရင်ခွင်',
    'kwint hlut': 'ခွင့်လွှတ်',
    'sa kar': 'စကား',
    's kar': 'စကား',
    'nan': 'နန်', 
    'yng': 'ရောင်',
    'a he': 'အဟီ',
    'hint': 'ဟင့်',
    'hoon': 'ဟွန်',
    'hon': 'ဟွန်',
    'hont': 'ဟွန့်',
    'mi mi ko ko': 'မိမ်ိကိုယ်ကို',
    'mi mi ko mi mi': 'မိမ်ိကိုယ်မိမိ',
    'kho': 'ကိုယ်',
    'kko': 'ကိုယ်',
    'ko ko': 'ကိုကို',
    'chay khan': 'အခြေခံ',
    'khou': 'ခေါ်',
    'naan': 'နမ်',
    'a nan': 'အနမ်း',
    'a naan': 'အနမ်း',
    'a nant': 'အနံ့',
    'a nant soe': 'အနံ့ဆိုး',
    'a nant soee': 'အနံ့ဆိုး',
    'nan dl': 'နံတယ်',
    'naan dl': 'နမ်းတယ်',
    'swal kine': 'ဆွဲကိုင်',
    'lat swal': 'လက်ဆွဲ',
    'bag': 'အိတ်',
    'wallet': 'အိတ်',
    'ka ma': 'ကမ',
    'kal': 'ကယ်',
    'hlay': 'လှေ',
    'sii': 'စီး',
    'yu twar': 'ယူသွား',
    'bal tu': 'ဘယ်သူ',
    'bl tu': 'ဘယ်သူ',
    'ngal': 'ငယ်',
    'ngae': 'ငယ်',
    'kyyo': 'ကြို',
    'yet': 'ရပ်',
    'sho': 'ရှို',
    'a ma lay': 'အမလေ',
    'la sho': 'လားရှို',
    'lar sho': 'လားရှို',
    'ka lay': 'ကလေး',
    'gyaw': 'ဂျော်',
    'gwi': 'ဂျွီ',
    'gwal': 'ဂွဲ',
    'zwe ka bin': 'ဇွဲကပင်',
    'lhae': 'လှည်',
    'kwe':'ကွီး',
    'thit sar': 'သစ္စာ',
    'chay': 'ခြေ',
    'pa': 'ပ',
    'kyate': 'ကြိတ်',
    'yate': 'ရိတ်',
    'yian': 'ရိန်',
    'sa yate': 'စရိတ်',
    'hla': 'လှ',
    'main': 'မိန်',
    'year': 'နှစ်',
    'nit': 'နှစ်',
    'taw yar': 'တော်ရာ',
    'vitamin': 'ဗီတာမင်',
    'nhite': 'နှိုက်',
    'nite': 'နှုက်',
    'nhit': 'နှစ်',
    'ywat': 'ရွက်',
    'ywet': 'ရွတ်',
    'saung ywat': 'ဆောင်ရွက်',
    'sg ywat': 'ဆောင်ရွက်',
    'sg': 'စောင်',
    'saaung': 'ဆောင်',
    'shint': 'ရှင့်',
    'byar': 'ဗျာ',
    'byar myar': 'ဗြာများ',
    'khin byar': 'ခဗျာ',
    'bya': 'ဗျ',
    'bye': 'ဘိုင်',
    'ka byar': 'ခဗျာ',
    'hein': 'ဟိန်',
    'hlyat': 'လျှက်',
    'myo nae': 'မြို့နယ်',
    'myo nal': 'မြို့နယ်',
    'htan ta bin': 'ထန်းတပင်',
    'htan ta pin': 'ထန်းတပင်',
    'htan hlyat': 'ထန်းလျှက်',
    'tan yaw zin': 'သံယောဇင်',
    'lu': 'လူ',
    'ma yu': 'မယူ',
    'tan yaw zin': 'သံယာဇဥ်',
    'kate': 'ကိတ်',
    'kathy': 'ကေတီ',
    'myat kathy': 'မြတ်ကေတီ',
    'kate sa': 'ကိစ္စ',
    'pyae sone': 'ပြည့်စုံ',
    'pyae sone shin': 'ပြည့်စုံသျှင်',
    'swun': 'စွံ',
    'swunt': 'စွံ့',
    'swun hlut': 'စွန်လွှတ်',
    'swunt sar': 'စွန့်စား',
    'swunt ser': 'စွန့်စား',
    'zone': 'ဇုန်',
    'bwe': 'ဘွယ်',
    'bwae': 'ဗွေ',
    'bwin': 'ဗွေ',
    'bwain': 'ဗွေ',
    'bwaie': 'ဗွေ',
    'lun':'လွန်',
    'na': 'နှ',
    'nha': 'နှ',
    'nhate': 'နှပ်',
    'htaw': 'ထော်',
    'taw': 'တော်',
    'phar': 'ဖာ',
    'nha lone': 'နှလုံး',
    'na lone': 'နှလုံး',
    'na lone tr': 'နှလုံးသား',
    'nha lone tr': 'နှလုံးသား',
    'nha lone tar': 'နှလုံးသား',
    'na lone tar': 'နှလုံးသား',
    'paing': 'ပိုင်',
    'paing yu': 'ပိုင်ယူ',
    'paing yuu': 'ပိုင်ယူ',
    'htr':'ထာ',
    'htar':'ထာ',
    'sut': 'စွပ်',
    'do': 'တို့',
    'pone sann': 'ပုံဆန်း',
    'chel': 'ချယ်',
    'kat': 'ကပ်',
    'cat': 'ကပ်',
    'choe': 'ချို',
    'phaung': 'ဖြောင်',
    'phya': 'ဖျ',
    'phae': 'ဖြေ',
    'phyae': 'ဖြေ',
    'tar won': 'တာဝန်',
    'tar win': 'တာဝန်',
    'htoke': 'ထုတ်',
    'htote': 'ထုပ်',
    'hlut': 'လွှတ်',
    'san lo ll': 'ဆန်းလို့လဲ',
    'sann lo ll': 'ဆန်းလို့လဲ',
    'bal lout sann lo ll': 'ဘယ်လောက်ဆန်းလို့လဲ',
    'eain gyi': 'အင်္ကျီ',
    'in gyi': 'အင်္ကျီ',
    'eain gye': 'အင်္ကျီ',
    'in gyi': 'အင်္ကျီ',
    'inn kyinn': 'အင်ကြင်း',
    'khat': 'ခဲ့',
    'khet': 'ခက်',
    'khat dl': 'ခက်တယ်',
    'a yan khat': 'အရမ်းခက်',
    'ma khat': 'မခက်',
    'min nanda': 'မင်နန္ဒာ',
    'nanda': 'မင်နန္ဒာ',
    'mane': 'မိန်',
    'thae': 'သည်',
    'a mhu te': 'အမူသည်',
    'a mhu the': 'အမူသည်',
    'a mhu de': 'အမူသည်',
    'a mu de': 'အမူသည်',
    'a mu the': 'အမူသည်',
    'a mu te': 'အမူသည်',
    'nay taw': 'နေသော',
    'myaw': 'မျော်',
    'mhyaw': 'မျော်',
    'lint': 'လင့်',
    'myaw lint': 'မျှော်လင့်',
    'khaw': 'ခေါ်',
    'kaw': 'ကော်',
    'chat': 'ချက်',
    'chyate': 'ချိပ်',
    'chate': 'ချိတ်',
    'mhu': 'မှု',
    'hmu': 'မူ',
    'poe': 'ပိုး',
    'nar': 'နာ',
    'bike': 'ဗိုက်',
    'pyout': 'ပျော့',
    'ar pyor': 'အားပျော့',
    'arr pyor': 'အားပျော့',
    'arr pyaw': 'အားပျော့',
    'mee': 'မီး',
    'a yat pu': 'အရပ်ပု',
    'a yet pu': 'အရပ်ပု',
    'a yan pu': 'အရမ်းပူ',
    'hot': 'ဟော့',
    'beer': 'ဘီယာ',
    'laung': 'လောင်',
    'ae': 'အဲ',
    'ae di': 'အဲ့',
    'a mhu thae': 'မမူ့သည်',
    'ku to': 'ကုသိုလ်',
    'ku tho': 'ကုသိုလ်',
    'tho': 'သိုလ်',
    'doke kha': 'ဒုက္ခ',
    'nar lae': 'နားလည်',
    'nar le': 'နားလည်',
    'nr lae': 'နားလည်',
    'nr le': 'နားလည်',
    'nar ll': 'နားလည်',
    'nar ll': 'နားလည်',
    'nr ll': 'နားလည်',
    'nr ll': 'နားလည်',
    'nar ll ll': 'နားလည်လား',
    'nar ll ll': 'နားလည်လား',
    'nr ll ll': 'နားလည်လား',
    'nr ll ll': 'နားလည်လား',
    'nr': 'နာ',
    'dan yar': 'ဒရာ',
    'pay sat': 'ပေးဆက်',
    'payy sat': 'ပေးဆက်',
    'academy': 'အကယ်ဒမီ',
    'bat': 'ဘက်',
    'kway': 'ကွေ',
    'kyway': 'ကြွေ',
    'sayyy': 'ဆေး',
    'sleep': 'အိပ်',
    'chike': 'ခြိုက်',
    'myay': 'မြေ',
    'wah': 'ဝါ',
    'thu ra': 'သူရ',
    'chaay': 'ချေ',
    'ngwe chay': 'ငွေချေ',
    'open': 'ဖွင့်',
    'moti': 'motivation ',
    'sa yar won': 'ဆရာဝန်',
    'sa yar ma': 'ဆရာမ',
    'sa yar nak': 'ဆရာနဲ့',
    'sa yar nat': 'ဆရာနဲ့',
    'sa yar net': 'ဆရာနဲ့',
    'sa yar nek': 'ဆရာနဲ့',
    'zin': 'ဇင်',
    'nyan': 'ညံ',
    'kay': 'ကေ',
    'ka thy': 'ကေတီ',
    'kay thy': 'ကေတီ',
    'thi ha': 'သီဟ',
    'ph': 'ဖုန်း',
    'pm': 'private message',
    '2358':'爱上我吧',
    '520':'我爱你',
    'kwel': 'ကွဲ',
    'thae kwal': 'သည်းကွဲ',
    'a thae kwal': 'အသည်းကွဲ',
    'swal': 'စွဲ',
    'phan sar': 'ဖမ်းစား',
    'oat': 'အုပ်',
    'ote': 'အုတ်',
    'oak': 'အုတ်',
    'swel': 'ဆွဲ',
    'sar yayy sayar': 'စာရေးဆရာ',
    'sar yayy sayar ma': 'စာရေးဆရာမ',
    'sar yayy sayar m': 'စာရေးဆရာမ',
    'sar yay sayar': 'စာရေးဆရာ',
    'sar yay sayar ma': 'စာရေးဆရာမ',
    'sar yay sayar m': 'စာရေးဆရာမ',
    'pan chi sayar': 'ပန်းချီဆရာ',
    'nga sayar': 'ငါ့ဆရာ',
    'thu sayar': 'သူ့ဆရာ',
    'ak sayar': 'အဲ့ဆရာ',
    'at sayar': 'အဲ့ဆရာ',
    'a sayar': 'အဲ့ဆရာ',
    'sayar lote': 'ဆရာလုပ်',
    'sayar ma lote': 'ဆရာမလုပ်',
    'n': 'န',
    'swal myae': 'ဆွဲမြဲ',
    'swel myae': 'ဆွဲမြဲ',
    'swal myal': 'ဆွဲမြဲ',
    'swel myal': 'ဆွဲမြဲ',
    'ka bar': 'ဘမ္ဘာ',
    'di tant': 'တည်တန့်',
    'ti tant': 'တည်တန့်',
    'saay': 'ဆေး',
    'say pay': 'ဆေပေး',
    'sayy pay': 'ဆေးပေး',
    'lan ma daw': 'လမ်းမတော်',
    'ka sun': 'ကစွန်း',
    'ka sun ywet kyaw': 'ကစွန်းရွက်ကြော်',
    'shyun': 'ရွှန်',
    'suaun': 'ဆွမ်',
    'suan': 'ဆွမ်',
    'sun': 'ဆွန်',
    'shun': 'ရွှန်',
    'syun': 'စွန်',
    'hlu': 'လှူ',
    'hu': 'ဟု',
    'huu': 'ဟူ',
    'huuu': 'ဟူး',
    'hyu': 'ဟူး',
    'hyuu': 'ဟူး',
    'hyg': 'ဟဲအကာင်',
    'ahw': 'သြ',
    'yew': '၍',
    'we': 'ဝီ',
    'ywe': 'ရွဲ',
    'pote sa': 'ပုစ္တာ',
    'pote sar': 'ပုစ္တာ',
    'shout ma': 'လျှောက်မ', // လျှောက်မပြစ်နဲ့
    'shout lote': 'လျှောက်လုပ်', // လျှောက်လုပ်ပြစ်နဲ့
    'shout lode': 'လျှောက်လုပ်', // လျှောက်လုပ်ပြစ်နဲ့
    'shout hlwar': 'လျှောက်လျွှာ', // လျှောက်လုပ်ပြစ်နဲ့
    'yite': 'ရိုက်',
    'yite htae': 'ရိုက်ထည့်',
    'yike': 'ရိုက်',
    'yike htae': 'ရိုက်ထည့်',
    'paaw': 'ပေါ်',
    'pouk': 'ပေါက်',
    'hlaw': 'လှော်',
    'gf': 'ရည်စား',
    'bf': 'ရည်စား',
    'fg': 'friend girl',
    'fb': 'facebook',
    'vc': 'video call',
    'pc': 'private chat',
    'mm': 'myanmar', 
    'cn': 'china',
    'py': 'ပေ',
    // 'ra': 'ရ',
    '1': '၁',
    '2': '၂',
    '3': '၃',
    '4': '၄',
    '5': '၅',
    '6': '၆',
    '7': '၇',
    '8': '၈',
    '9': '၉',
    '0': '၀',
    '.': '။',
};

// console.log(MyanglishToMyanmarDict);
let dataOptimized = false;
let TotalDataCount = 0;
let DataSet = {
    '1': {}
};

const MyanmarToMyanglishDataSet = {
    '1': {}
};

const MyanmarAlphabet = [
    'က','ခ','ဂ','ဃ','င',
    'စ','ဆ','ဇ','ဈ','ည',
    'ဋ','ဌ','ဍ','ဎ','ဏ',
    'တ','ထ','ဒ','ဓ','န',
    'ပ','ဖ','ဗ','ဘ','မ',
    'ယ','ရ','လ','ဝ','သ','ဟ',
    'ဠ','အ','ဢ','ဣ','ဤ','ဥ',
    'ဩ', 'ဿ', '၌', '၍', '၎',
    '၏','ၮ','႟','ဧ',
    '၁','၂','၃','၄','၅','၆','၇','၈','၉','၀'
];
const MyanmarVowelSound = [
    // 'ခ်', 'ခံ', 'ခ့', 'ခး', 'ခ္',
    '်', 'ံ', '့', 'း', '္',
    // 'ာ'
];




function isBurmeseVowel(str) {
    // const key = str.slice(-1);
    // return key == 'း' || key == "ံ" || key == '့';
    // return str.includes('း') || str.includes("ံ") || str.includes('့');

    if(str.includes('း')) return {
        type: 'double',
        originalValue: str.slice(0, -1),
        symbol: null
    }

    if(str.includes('့')) return {
        type: '.',
        originalValue: str.slice(0, -1),
        symbol: 'k'
    }

    return false;
    
}





function optimizeData() {
     Object.entries(MyanglishToMyanmarDict).sort(([aKey, aValue], [bKey, bValue]) => {
        return bKey.length - aKey.length;
    }).forEach(([key, value]) => {
        const split = key.split(' ');
        const keyLength = split.length;
        if(DataSet[keyLength]){
            DataSet[keyLength][key] = value;
            DataSet['1'][split.join('')] = value;
        }else {
            DataSet[keyLength] = { 
                [key]: value
            };
        }
        TotalDataCount++;
    });

    

    let Temp = {};
    Object.entries(MyanglishToMyanmarDict).forEach(([key, value]) => {
        Temp[value] = key;
    });
    Object.entries(Temp).sort(([aKey, aValue], [bKey, bValue]) => {
        return bKey.length - aKey.length;
    }).forEach(([key, value]) => {
        const len = myanmarWordSpliter(key).length;
        if(MyanmarToMyanglishDataSet[len]){
            MyanmarToMyanglishDataSet[len][key] = value;
        }else {
            MyanmarToMyanglishDataSet[len] = {
                [key]: value
            };
        }
    });
    // Temp == null;
    console.log(MyanmarToMyanglishDataSet);
    // console.log(DataSet);
    dataOptimized = true;
}





function detectVowel(token){
    // detect : 
    function detectDoubleSound(token){
        const doubleSound = token.slice(-2).split('');
        return doubleSound[0] == doubleSound[1] && token.length > 2 && doubleSound[0] !== 'k';
    }

    if(DataSet['1'][token]){
        return {
            sound: '',
            originalValue: token
        }
    }

    // detect : with token ending with double keyword, such as ending with "nn", "yayy"
    if(detectDoubleSound(token)){
        return {
            sound: 'း',
            originalValue: token.slice(0, -1)
        }
    }

    // detect ့ with token ending with k
    if(token.slice(-1).toLowerCase() == 'k' || token.slice(-1).toLowerCase() == 't'){
        return {
            sound: '့',
            originalValue: token.slice(0, -1)
        }
    }

    return {
        sound: '',
        originalValue: token
    }
}
function characterSimilarity(text1, text2){
    if(text1 == text2) return {
        rate: 1,
        input: {text1, text2}
    }

    const text1Split = text1.replace(/ /g, '').split('');
    const text2Split = text2.replace(/ /g, '').split('');

    // chars test
    const text1Chars = {};
    const text2Chars = {};
    text1Split.forEach(c => text1Chars[c] ? text1Chars[c] = text1Chars[c] + 1 : text1Chars[c] = 1);
    text2Split.forEach(c => text2Chars[c] ? text2Chars[c] = text2Chars[c] + 1 : text2Chars[c] = 1);

    let text1ToText2Score = 0;
    let text2ToText1Score = 0;
    Object.entries(text1Chars).forEach(([key, value]) => {
        const t2CharScore = text2Chars[key] || 0;
        text1ToText2Score = t2CharScore ? text1ToText2Score + (value / t2CharScore) : text1ToText2Score;
    });
    Object.entries(text2Chars).forEach(([key, value]) => {
        const t1CharScore = text1Chars[key] || 0;
        text2ToText1Score = t1CharScore ? text2ToText1Score + (value / t1CharScore) : text2ToText1Score;
    });
    const mean = (text1ToText2Score + text2ToText1Score) / 2;
    const lengthMean = (text1.length + text2.length) / 2;

    return {
        rate: mean / lengthMean,
        input: {
            text1, text2
        }
    }
}
function phraseSimilarity(text1, text2){
    if(text1 == text2) return {
        rate: 1,
        input: {text1, text2}
    }

    const text1pharase = text1.split(' ').filter(t => t != '');
    const text2pharase = text2.split(' ').filter(t => t != '');

    const text1PharseToText2 = {};
    text1pharase.forEach(phrase1 => {
        text2pharase.forEach(phrase2 => {
            if(phrase1 == phrase2){
                text1PharseToText2[phrase1] = !!text1PharseToText2[phrase1] ? text1PharseToText2[phrase1] + 1 : 1;
            }
        });
        !text1PharseToText2[phrase1] && (text1PharseToText2[phrase1] = 0);
    });

    const text2PharseToText1 = {};
    text2pharase.forEach(phrase2 => {
        text1pharase.forEach(phrase1 => {
            if(phrase1 == phrase2){
                text2PharseToText1[phrase2] = !!text2PharseToText1[phrase2] ? text2PharseToText1[phrase2] + 1 : 1;
            }
        });
        !text2PharseToText1[phrase2] && (text2PharseToText1[phrase2] = 0);
    });



    const score = (() => {
        const ent1 = Object.entries(text1PharseToText2);
        const ent2 = Object.entries(text2PharseToText1);

        const sc1 = (() => {
            let sc = 0;
            ent1.forEach(([key, value]) => {
                const t2Val = text2PharseToText1[key] || 0;
                sc = sc + (value + t2Val) / 2;
            });
            return sc / ((ent1.length + ent2.length) / 2);
        })();

        const sc2 = (() => {
            let sc = 0;
            ent2.forEach(([key, value]) => {
                const t1Val = text1PharseToText2[key] || 0;
                sc = sc + (value + t1Val) / 2;
            });
            return sc / ((ent1.length + ent2.length) / 2);
        })();

        return (sc1 + sc2) / 2;
    })();



    // console.log(text1PharseToText2);
    // console.log(text2PharseToText1);
    // console.log('score', score);

    return {
        rate: score,
        input: {
            text1, text2
        }
    };
}







function myanmarWordSpliter(text){
    // func.myanmarWordSpliter("ခြှောက်ပြစ်ကင်းသဲလဲဆင်ကိစ္စကိုစန္ဒာသင်္ကြန်အန္ဒြေရမရှိဘူးအတွေးအခေါ်မရှိကြဘူး");

    //
    // Splitting myanmar sentence will generate following
    // result
    // ['ခ', 'ြ', 'ှ', 'ေ', 'ာ', 'က', '်', 'ပ', 'ြ', 'စ', '်', 'က', 'င', '်', 'း', 'သ', 'ဲ', 'လ', 'ဲ', 'ဆ', 'င', '်', 'က', 'ိ', 'စ', '္', 'စ', 'က', 'ိ', 'ု', 'စ', 'န', '္', 'ဒ', 'ာ', 'သ', 'င', '်', '္', 'က', 'ြ', 'န', '်', 'အ', 'န', '္', 'ဒ', 'ြ', 'ေ', 'ရ', 'မ', 'ရ', 'ှ', 'ိ', 'ဘ', 'ူ', 'း', 'အ', 'တ', 'ွ', 'ေ', 'း', 'အ', 'ခ', 'ေ', 'ါ', '်', 'မ', 'ရ', 'ှ', 'ိ', 'က', 'ြ', 'ဘ', 'ူ', 'း']
    //
    const split = text.split('');
    const word = [];

    // THEN
    // general group အသက် with အက္ခရာ
    // 
    // this will concat with generalization of myanmar consonant with vouwel
    // by detecting base က္ခရာ and concat with အသက်
    // output result will be
    // ['ခြှော', 'က်', 'ပြ', 'စ်', 'က', 'င်း', 'သဲ', 'လဲ', 'ဆ', 'င်', 'ကိ', 'စ္', 'စ', 'ကို', 'စ', 'န္', 'ဒာ', 'သ', 'င်္', 'ကြ', 'န်', 'အ', 'န္', 'ဒြေ', 'ရ', 'မ', 'ရှိ', 'ဘူး']
    //
    // 
    let tmp = '';
    for(let i = 0; i < split.length; i++){
        const char = split[i];
        if(char == ' ' && i > 0){
            word.push(tmp);
            word.push(' ');
            tmp = '';
            continue;
        }

        if(MyanmarAlphabet.includes(char) && i > 0){
            tmp.length > 0 && word.push(tmp);
            tmp = char;
        }else {
            tmp = tmp + char;
        }
        
        // push end of word
        if(i == split.length - 1) {
            word.push(tmp);
            tmp = '';
        }
    }


    // THEN
    // concat with အသတ်
    // 
    // this will concat with generalization of myanmar consonant with vouwel
    // ['ကော','က်', 'ရ', 'င်', 'ကျိုး', 'ရ', 'စန္', 'ဒာ'] => ['ကောက်', 'ရင်', 'ကျိုး', 'ရ', 'စန္', 'ဒာ']
    // output result will be
    // ['ခြှောက်', 'ပြစ်', 'ကင်း', 'သဲ', 'လဲ', 'ဆင်', 'ကိစ္', 'စ', 'ကို', 'စန္', 'ဒာ', 'သင်္', 'ကြန်', 'အန္', 'ဒြေ', 'ရ', 'မ', 'ရှိ', 'ဘူး']
    //
    // 
    let len = word.length;
    for(let i = 0; i < len; i++){
        const wd = word[i];
        if(!wd) continue;

        if(wd.length >= 2 && wd.length <= 3){
            if(MyanmarVowelSound.includes(wd.split('')[1]) && word[i - 1] != ' '){
                word[i - 1] = word[i - 1] + wd;
                word.splice(i, 1);
                len--;
            }
        }
    }


    // THEN
    // concat with ပဆင့်
    // 
    // this will concat with generalization of myanmar consonant with vouwel
    // ['ကောက်', 'ရင်', 'ကျိုး', 'ရ', 'စန္', 'ဒာ'] => ['ကောက်', 'ရင်', 'ကျိုး', 'ရ', 'စန္ဒာ'] 
    // output result will be
    // ['ခြှောက်', 'ပြစ်', 'ကင်း', 'သဲ', 'လဲ', 'ဆင်', 'ကိစ္စ', 'ကို', 'စန္ဒာ', 'သင်္ကြန်', 'အန္ဒြေ', 'ရ', 'မ', 'ရှိ', 'ဘူး', 'အ', 'တွေး', 'အ', 'ခေါ်', 'မ', 'ရှိ', 'ကြ', 'ဘူး']
    //
    // 
    for(let i = 0; i < word.length; i++){
        const wd = word[i];
        if(wd.includes('္')){
            word[i + 1] = wd + word[i + 1];
            word.splice(i, 1);
        }
    }
    
    return word;
}






var func = {
    convertToBurmese: (string) => {
        if(!dataOptimized) optimizeData();

        let str = '';
        string = string.toLowerCase();
        string = string.replace(/\n/g, '');
        if (string.includes(' ')) {
            const tokens = string.trim().split(' ');
            // console.log(tokens);
            for(let i = 0; i < tokens.length; i++){
                const groupIndex = tokens.length - i <= 5 ? tokens.length - i : 5;
                if(groupIndex > 1){
                    for(let j = groupIndex; j > 0; j--) {
                        const phrase = tokens.slice(i, i + j);
                        const matchedIndex = DataSet[phrase.length];
                        if(matchedIndex){
                            const re = matchedIndex[phrase.join(' ')];
                            if(re){
                                str = str + re;
                                i = i + j - 1;
                                break;
                            }

                            const groupPhrase = phrase.join('');
                            const mat = DataSet['1'][groupPhrase];
                            if(mat){
                                str = str + mat;
                                i = i + j - 1;
                                break;
                            }
                        }
                        if(j == 1){
                            matchSingleToken(tokens[i]);
                            break;
                        }
                    }
                }else {
                    matchSingleToken(tokens[i]);
                }
            }
            return str;
        } else {
            return matchSingleToken(string);
        }


        function matchSingleToken(token){
            const vol = detectVowel(token);
            // console.log(vol);
            if (DataSet['1'][vol.originalValue]) {
                str = str + DataSet['1'][vol.originalValue] + vol.sound;
            } else {
                if(token.length == 0){
                    str = str + ' ';
                }else {
                    str = str + `{${token}}`;
                }
            }
            return str;
        }
    },
    convertToMyanglish: (mmString) => {
        if(!dataOptimized) optimizeData();
        
        const tokens = myanmarWordSpliter(mmString);
        // console.log(tokens);
        let str = '';
        for(let i = 0; i < tokens.length; i ++){
            const groupIndex = tokens.length - i <= 5 ? tokens.length - i : 5;
            for(let j = groupIndex; j > 0; j--){
                const splitToken = tokens.slice(i, i + j);
                const phrase = splitToken.join('');
                const matched = MyanmarToMyanglishDataSet[splitToken.length][`${phrase}`];
                if(matched){
                    appendStr(matched);
                    i = i + j - 1;
                    break;
                }

                if(j == 1){
                    matchSingleToken(phrase);
                    break;
                }
            }
        }

        function matchSingleToken(token){
            const includeSpecialVowel = isBurmeseVowel(token);
            if(includeSpecialVowel){
                const mat = MyanmarToMyanglishDataSet['1'][includeSpecialVowel.originalValue];
                if(mat){
                    if(includeSpecialVowel.type == 'double')
                        appendStr(mat + mat.slice(-1));
                    else if(includeSpecialVowel.type == '.')
                        appendStr(mat + 'k');
                    else
                        appendStr(mat);

                }else if(token == ' ' && token.length == 1) {
                    appendStr(' ');
                }else {
                    appendStr(mat || `{${token}}`);
                }
            }else {
                const mat = MyanmarToMyanglishDataSet['1'][token];
                if(token == ' ' && token.length == 1) {
                    appendStr(' ');
                }else {
                    appendStr(mat || `{${token}}`);
                }
            }
            return str;
        }

        function appendStr(append){
            str = str + (str.length > 0 ? ' ' : '') + append;
        }
        return str;
    },
    getDatasetCount: () => {
        return TotalDataCount;
    },
    textSimilarity: (text1, text2) => {
        // if(text1 == text2) return {
        //     rate: 1,
        //     input: {
        //         text1, text2
        //     }
        // }

        // const text1Split = text1.split('');
        // const text2Split = text2.split('');

        // const charSimilarity = characterSimilarity(text1, text2);


        const charSimilar = characterSimilarity(text1, text2);
        const phraseSimilar = phraseSimilarity(text1, text2);

        return (phraseSimilar.rate + charSimilar.rate) /2;
    },
    myanmarWordSpliter
};

module.exports = func;
